<?php

/*
 _      _          _____    _____    ___  _____
| \    / |  \  /  |        |     |  |       |
|  \  /  |   \/   |_____   |     | _|__     |
|   \/   |   /          |  |     |  |       |
|        |  /     ______|  |_____|  |       |
*/

namespace pocketmine\item;

use pocketmine\block\Block;
use pocketmine\block\Flower;
use pocketmine\entity\Entity;
use pocketmine\entity\Squid;
use pocketmine\entity\Villager;
//use pocketmine\entity\Zombie;
use pocketmine\inventory\Fuel;
use pocketmine\item\enchantment\Enchantment;
use pocketmine\level\Level;
use pocketmine\nbt\tag\Enum;
use pocketmine\nbt\tag\ShortTag;
use pocketmine\nbt\tag\StringTag;
use pocketmine\utils\Binary;
use pocketmine\nbt\tag\ByteTag;
use pocketmine\nbt\tag\IntTag;
use pocketmine\Player;
use pocketmine\nbt\tag\Compound;
use pocketmine\nbt\NBT;
use pocketmine\Server;
use pocketmine\utils\Config;

class Item{

	private static $cachedParser = null;
	private static $itemBlockClass = ItemBlock::class;

	/**
	 * @param $tag
	 * @return Compound
	 */
	private static function parseCompound($tag){
		if(self::$cachedParser === null){
			self::$cachedParser = new NBT(NBT::LITTLE_ENDIAN);
		}

		self::$cachedParser->read($tag);
		return self::$cachedParser->getData();
	}

	/**
	 * @param Compound $tag
	 * @return string
	 */
	private static function writeCompound(Compound $tag){
		if(self::$cachedParser === null){
			self::$cachedParser = new NBT(NBT::LITTLE_ENDIAN);
		}

		self::$cachedParser->setData($tag);
		return self::$cachedParser->write(true);
	}
	const CREATIVE_GROUP_NONE = 0xffffffff;
	const CREATIVE_GROUP_PLANKS = 0;
	const CREATIVE_GROUP_WALLS = 1;
	const CREATIVE_GROUP_FENCE = 2;
	const CREATIVE_GROUP_FENCEGATE = 3;
	const CREATIVE_GROUP_STAIRS = 4;
	const CREATIVE_GROUP_DOOR = 5;
	const CREATIVE_GROUP_TRAPDOOR = 6;
	const CREATIVE_GROUP_GLASS = 7;
	const CREATIVE_GROUP_GLASSPANE = 8;
	const CREATIVE_GROUP_SLAB = 9;
	const CREATIVE_GROUP_STONEBRICK = 10;
	const CREATIVE_GROUP_SANDSTONE = 11;
	const CREATIVE_GROUP_WOOL = 12;
	const CREATIVE_GROUP_WOOLCARPET = 13;
	const CREATIVE_GROUP_STAINEDCLAY = 14;
	const CREATIVE_GROUP_ORE = 15;
	const CREATIVE_GROUP_STONE = 16;
	const CREATIVE_GROUP_LOGS = 17;
	const CREATIVE_GROUP_LEAVES = 18;
	const CREATIVE_GROUP_SAPLING = 19;
	const CREATIVE_GROUP_SEED = 20;
	const CREATIVE_GROUP_CROP = 21;
	const CREATIVE_GROUP_GRASS = 22;
	const CREATIVE_GROUP_FLOWER = 23;
	const CREATIVE_GROUP_DYE = 24;
	const CREATIVE_GROUP_MUSHROOM = 25;
	const CREATIVE_GROUP_MOBEGG = 26;
	const CREATIVE_GROUP_HELMET = 27;
	const CREATIVE_GROUP_CHESTPLATE = 28;
	const CREATIVE_GROUP_LEGGINGS = 29;
	const CREATIVE_GROUP_BOOTS = 30;
	const CREATIVE_GROUP_SWORD = 31;
	const CREATIVE_GROUP_AXE = 32;
	const CREATIVE_GROUP_PICKAXE = 33;
	const CREATIVE_GROUP_SHOVEL = 34;
	const CREATIVE_GROUP_HOE = 35;
	const CREATIVE_GROUP_ARROW = 36;
	const CREATIVE_GROUP_COOKEDFOOD = 37;
	const CREATIVE_GROUP_MISCFOOD = 38;
	const CREATIVE_GROUP_BED = 39;
	const CREATIVE_GROUP_ANVIL = 40;
	const CREATIVE_GROUP_CHEST = 41;
	const CREATIVE_GROUP_SIGN = 42;
	const CREATIVE_GROUP_RAIL = 43;
	const CREATIVE_GROUP_MINECART = 44;
	const CREATIVE_GROUP_BOAT = 45;
	const CREATIVE_GROUP_CONCRETE = 46;
	const CREATIVE_GROUP_CONCRETEPOWDER = 47;

	private static $creativeGroupData = [
		self::CREATIVE_GROUP_PLANKS => ['name' => 'itemGroup.name.planks', 'item' => self::PLANK],
		self::CREATIVE_GROUP_WALLS => ['name' => 'itemGroup.name.walls', 'item' => self::COBBLESTONE_WALL],
		self::CREATIVE_GROUP_FENCE => ['name' => 'itemGroup.name.fence', 'item' => self::FENCE],
		self::CREATIVE_GROUP_FENCEGATE => ['name' => 'itemGroup.name.fenceGate', 'item' => self::FENCE_GATE],
		self::CREATIVE_GROUP_STAIRS => ['name' => 'itemGroup.name.stairs', 'item' => self::COBBLE_STAIRS],
		self::CREATIVE_GROUP_DOOR => ['name' => 'itemGroup.name.door', 'item' => self::WOODEN_DOOR],
		self::CREATIVE_GROUP_TRAPDOOR => ['name' => 'itemGroup.name.trapdoor', 'item' => self::TRAPDOOR],
		self::CREATIVE_GROUP_GLASS => ['name' => 'itemGroup.name.glass', 'item' => self::GLASS],
		self::CREATIVE_GROUP_GLASSPANE => ['name' => 'itemGroup.name.glassPane', 'item' => self::GLASS_PANE],
		self::CREATIVE_GROUP_SLAB => ['name' => 'itemGroup.name.slab', 'item' => self::SLAB],
		self::CREATIVE_GROUP_STONEBRICK => ['name' => 'itemGroup.name.stoneBrick', 'item' => self::STONE_BRICK],
		self::CREATIVE_GROUP_SANDSTONE => ['name' => 'itemGroup.name.sandstone', 'item' => self::SANDSTONE],
		self::CREATIVE_GROUP_WOOL => ['name' => 'itemGroup.name.wool', 'item' => self::WOOL],
		self::CREATIVE_GROUP_WOOLCARPET => ['name' => 'itemGroup.name.woolCarpet', 'item' => self::CARPET],
		self::CREATIVE_GROUP_STAINEDCLAY => ['name' => 'itemGroup.name.stainedClay', 'item' => self::CLAY_BLOCK],
		self::CREATIVE_GROUP_ORE => ['name' => 'itemGroup.name.ore', 'item' => self::IRON_ORE],
		self::CREATIVE_GROUP_STONE => ['name' => 'itemGroup.name.stone', 'item' => self::STONE],
		self::CREATIVE_GROUP_LOGS => ['name' => 'itemGroup.name.log', 'item' => self::LOG],
		self::CREATIVE_GROUP_LEAVES => ['name' => 'itemGroup.name.wood', 'item' => self::LEAVES],
		self::CREATIVE_GROUP_SAPLING => ['name' => 'itemGroup.name.sapling', 'item' => self::SAPLING],
		self::CREATIVE_GROUP_SEED => ['name' => 'itemGroup.name.seed', 'item' => self::SEEDS],
		self::CREATIVE_GROUP_CROP => ['name' => 'itemGroup.name.crop', 'item' => self::WHEAT],
		self::CREATIVE_GROUP_GRASS => ['name' => 'itemGroup.name.grass', 'item' => self::TALL_GRASS],
		self::CREATIVE_GROUP_FLOWER => ['name' => 'itemGroup.name.flower', 'item' => self::DANDELION],
		self::CREATIVE_GROUP_DYE => ['name' => 'itemGroup.name.dye', 'item' => self::DYE],
		self::CREATIVE_GROUP_MUSHROOM => ['name' => 'itemGroup.name.mushroom', 'item' => self::BROWN_MUSHROOM],
		self::CREATIVE_GROUP_MOBEGG => ['name' => 'itemGroup.name.mobEgg', 'item' => self::SPAWN_EGG],
		self::CREATIVE_GROUP_HELMET => ['name' => 'itemGroup.name.helmet', 'item' => self::LEATHER_CAP],
		self::CREATIVE_GROUP_CHESTPLATE => ['name' => 'itemGroup.name.chestplate', 'item' => self::LEATHER_TUNIC],
		self::CREATIVE_GROUP_LEGGINGS => ['name' => 'itemGroup.name.leggings', 'item' => self::LEATHER_PANTS],
		self::CREATIVE_GROUP_BOOTS => ['name' => 'itemGroup.name.boots', 'item' => self::LEATHER_BOOTS],
		self::CREATIVE_GROUP_SWORD => ['name' => 'itemGroup.name.sword', 'item' => self::WOODEN_SWORD],
		self::CREATIVE_GROUP_AXE => ['name' => 'itemGroup.name.axe', 'item' => self::WOODEN_AXE],
		self::CREATIVE_GROUP_PICKAXE => ['name' => 'itemGroup.name.pickaxe', 'item' => self::WOODEN_PICKAXE],
		self::CREATIVE_GROUP_SHOVEL => ['name' => 'itemGroup.name.shovel', 'item' => self::WOODEN_SHOVEL],
		self::CREATIVE_GROUP_HOE => ['name' => 'itemGroup.name.hoe', 'item' => self::WOODEN_HOE],
		self::CREATIVE_GROUP_ARROW => ['name' => 'itemGroup.name.arrow', 'item' => self::ARROW],
		self::CREATIVE_GROUP_COOKEDFOOD => ['name' => 'itemGroup.name.cookedFood', 'item' => self::COOKED_CHICKEN],
		self::CREATIVE_GROUP_MISCFOOD => ['name' => 'itemGroup.name.miscFood', 'item' => self::BREAD],
		self::CREATIVE_GROUP_BED => ['name' => 'itemGroup.name.bed', 'item' => self::BED],
		self::CREATIVE_GROUP_ANVIL => ['name' => 'itemGroup.name.anvil', 'item' => self::ANVIL],
		self::CREATIVE_GROUP_CHEST => ['name' => 'itemGroup.name.chest', 'item' => self::CHEST],
		self::CREATIVE_GROUP_SIGN => ['name' => 'itemGroup.name.sign', 'item' => self::SIGN],
		self::CREATIVE_GROUP_RAIL => ['name' => 'itemGroup.name.rail', 'item' => self::RAIL],
		self::CREATIVE_GROUP_MINECART => ['name' => 'itemGroup.name.minecart', 'item' => self::MINECART],
		self::CREATIVE_GROUP_BOAT => ['name' => 'itemGroup.name.firework', 'item' => self::BOAT],
		self::CREATIVE_GROUP_CONCRETE => ['name' => 'itemGroup.name.concrete', 'item' => 236],
		self::CREATIVE_GROUP_CONCRETEPOWDER => ['name' => 'itemGroup.name.concretepowder', 'item' => 237],
	];
	//All Block IDs are here too
	// NEW
	const NEWVERSION_TOTEM_OF_UNDYING = 558;
	const NEWVERSION_STONE = 1;
	const NEWVERSION_GRASS = 2;
	const NEWVERSION_DIRT = 3;
	const NEWVERSION_COBBLE = 4;
	const NEWVERSION_WOODEN_PLANKS = 5;
	const NEWVERSION_SAPLINGS = 6;
	const NEWVERSION_BEDROCK = 7;
	const NEWVERSION_WATER = 8;
	const NEWVERSION_STILL_WATER = 9;
	const NEWVERSION_LAVA = 10;
	const NEWVERSION_STILL_LAVA = 11;
	const NEWVERSION_SAND = 12;
	const NEWVERSION_GRAVEL = 13;
	const NEWVERSION_GOLD_ORE = 14;
	const NEWVERSION_IRON_ORE = 15;
	const NEWVERSION_COAL_ORE = 16;
	const NEWVERSION_TRUNK = 17;
	const NEWVERSION_LEAVE = 18;
	const NEWVERSION_SPONGE = 19;
	const NEWVERSION_GLASS = 20;
	const NEWVERSION_LAPIS_ORE = 21;
	const NEWVERSION_LAPIS_BLOCK = 22;
	const NEWVERSION_DISPENSER = 23;
	const NEWVERSION_SANDSTONE = 24;
	const NEWVERSION_NOTE_BLOCK = 25;
	const NEWVERSION_BED_BLOCK = 26;
	const NEWVERSION_POWERED_RAIL = 27;
	const NEWVERSION_DETECTOR_RAIL = 28;
	const NEWVERSION_STICKY_PISTON = 29;
	const NEWVERSION_COBWEB = 30;
	const NEWVERSION_TALL_GRASS = 31;
	const NEWVERSION_DEAD_BUSH = 32;
	const NEWVERSION_WOOL = 35;
	const NEWVERSION_DANDELION = 37;
	const NEWVERSION_RED_FLOWER = 38;
	const NEWVERSION_BROWN_MUSHROOM = 39;
	const NEWVERSION_RED_MUSHROOM = 40;
	const NEWVERSION_GOLD_BLOCK = 41;
	const NEWVERSION_IRON_BLOCK = 42;
	const NEWVERSION_DOUBLE_SLABS = 43;
	const NEWVERSION_SLABS = 44;
	const NEWVERSION_BRICKS_BLOCK = 45;
	const NEWVERSION_TNT = 46;
	const NEWVERSION_BOOKSHELF = 47;
	const NEWVERSION_MOSSY_STONE = 48;
	const NEWVERSION_OBSIDIAN = 49;
	const NEWVERSION_TORCH = 50;
	const NEWVERSION_FIRE = 51;
	const NEWVERSION_MONSTER_SPAWNER = 52;
	const NEWVERSION_OAK_WOODEN_STAIRS = 53;
	const NEWVERSION_CHEST = 54;
	const NEWVERSION_REDSTONE_WIRE = 55;
	const NEWVERSION_DIAMOND_ORE = 56;
	const NEWVERSION_DIAMOND_BLOCK = 57;
	const NEWVERSION_WORKBENCH = 58;
	const NEWVERSION_WHEAT_BLOCK = 59;
	const NEWVERSION_FARMLAND = 60;
	const NEWVERSION_FURNACE = 61;
	const NEWVERSION_LIT_FURNACE = 62;
	const NEWVERSION_SIGN_POST = 63;
	const NEWVERSION_WOOD_DOOR_BLOCK = 64;
	const NEWVERSION_LADDER = 65;
	const NEWVERSION_RAIL = 66;
	const NEWVERSION_COBBLESTONE_STAIRS = 67;
	const NEWVERSION_WALL_SIGN = 68;
	const NEWVERSION_LEVER = 69;
	const NEWVERSION_STONE_PRESSURE_PLATE = 70;
	const NEWVERSION_IRON_DOOR_BLOCK = 71;
	const NEWVERSION_WOODEN_PRESSURE_PLATE = 72;
	const NEWVERSION_REDSTONE_ORE = 73;
	const NEWVERSION_LIT_REDSTONE_ORE = 74;
	const NEWVERSION_REDSTONE_TORCH = 75;
	const NEWVERSION_REDSTONE_TORCH_ACTIVE = 76;
	const NEWVERSION_STONE_BUTTON = 77;
	const NEWVERSION_SNOW_LAYER = 78;
	const NEWVERSION_ICE = 79;
	const NEWVERSION_SNOW_BLOCK = 80;
	const NEWVERSION_CACTUS = 81;
	const NEWVERSION_CLAY_BLOCK = 82;
	const NEWVERSION_SUGARCANE_BLOCK = 83;
	const NEWVERSION_JUKEBOX = 84;
	const NEWVERSION_FENCE = 85;
	const NEWVERSION_PUMPKIN = 86;
	const NEWVERSION_NETHERRACK = 87;
	const NEWVERSION_SOUL_SAND = 88;
	const NEWVERSION_GLOWSTONE_BLOCK = 89;
	const NEWVERSION_PORTAL = 90;
	const NEWVERSION_JACK_O_LANTERN = 91;
	const NEWVERSION_CAKE_BLOCK = 92;
	const NEWVERSION_REDSTONE_REPEATER_BLOCK = 93;
	const NEWVERSION_REDSTONE_REPEATER_BLOCK_ACTIVE = 94;
	const NEWVERSION_INVISIBLE_BEDROCK = 95;
	const NEWVERSION_TRAPDOOR = 96;
	const NEWVERSION_MONSTER_EGG = 97;
	const NEWVERSION_STONE_BRICK = 98;
	const NEWVERSION_BROWN_MUSHROOM_BLOCK = 99;
	const NEWVERSION_RED_MUSHROOM_BLOCK = 100;
	const NEWVERSION_IRON_BARS = 101;
	const NEWVERSION_GLASS_PANEL = 102;
	const NEWVERSION_MELON_BLOCK = 103;
	const NEWVERSION_PUMPKIN_STEM = 104;
	const NEWVERSION_MELON_STEM = 105;
	const NEWVERSION_VINES = 106;
	const NEWVERSION_FENCE_GATE = 107;
	const NEWVERSION_BRICK_STAIRS = 108;
	const NEWVERSION_STONE_BRICK_STAIRS = 109;
	const NEWVERSION_MYCELIUM = 110;
	const NEWVERSION_LILY_PAD = 111;
	const NEWVERSION_NETHER_BRICK_BLOCK = 112;
	const NEWVERSION_NETHER_BRICK_FENCE = 113;
	const NEWVERSION_NETHER_BRICKS_STAIRS = 114;
	const NEWVERSION_NETHER_WART_BLOCK = 115;
	const NEWVERSION_ENCHANTMENT_TABLE = 116;
	const NEWVERSION_BREWING_STAND_BLOCK = 117;
	const NEWVERSION_CAULDRON_BLOCK = 118;
	const NEWVERSION_END_PORTAL = 120;
	const NEWVERSION_END_STONE = 121;
	const NEWVERSION_DRAGON_EGG = 122;
	const NEWVERSION_REDSTONE_LAMP = 123;
	const NEWVERSION_REDSTONE_LAMP_ACTIVE = 124;
	const NEWVERSION_DROPPER = 125;
	const NEWVERSION_ACTIVATOR_RAIL = 126;
	const NEWVERSION_COCOA = 127;
	const NEWVERSION_SANDSTONE_STAIRS = 128;
	const NEWVERSION_EMERALD_ORE = 129;
	const NEWVERSION_ENDER_CHEST = 130;
	const NEWVERSION_TRIPWIRE_HOOK = 131;
	const NEWVERSION_TRIPWIRE = 132;
	const NEWVERSION_EMERALD_BLOCK = 133;
	const NEWVERSION_SPRUCE_WOODEN_STAIRS = 134;
	const NEWVERSION_BIRCH_WOODEN_STAIRS = 135;
	const NEWVERSION_JUNGLE_WOODEN_STAIRS = 136;
	const NEWVERSION_BEACON = 138;
	const NEWVERSION_COBBLESTONE_WALL = 139;
	const NEWVERSION_FLOWER_POT_BLOCK = 140;
	const NEWVERSION_CARROT_BLOCK = 141;
	const NEWVERSION_POTATO_BLOCK = 142;
	const NEWVERSION_WOODEN_BUTTON = 143;
	const NEWVERSION_MOB_HEAD_BLOCK = 144;
	const NEWVERSION_ANVIL = 145;
	const NEWVERSION_TRAPPED_CHEST = 146;
	const NEWVERSION_WEIGHTED_PRESSURE_PLATE_LIGHT = 147;
	const NEWVERSION_WEIGHTED_PRESSURE_PLATE_HEAVY = 148;
	const NEWVERSION_REDSTONE_COMPARATOR_BLOCK = 149;
	const NEWVERSION_REDSTONE_COMPARATOR_BLOCK_POWERED = 150;
	const NEWVERSION_DAYLIGHT_SENSOR = 151;
	const NEWVERSION_REDSTONE_BLOCK = 152;
	const NEWVERSION_NETHER_QUARTZ_ORE = 153;
	const NEWVERSION_HOPPER_BLOCK = 154;
	const NEWVERSION_QUARTZ_BLOCK = 155;
	const NEWVERSION_QUARTZ_STAIRS = 156;
	const NEWVERSION_DOUBLE_WOODEN_SLABS = 157;
	const NEWVERSION_WOODEN_SLABS = 158;
	const NEWVERSION_STAINED_HARDENED_CLAY = 159;
	const NEWVERSION_STAINED_GLASS_PANE = 160;
	const NEWVERSION_LEAVE2 = 161;
	const NEWVERSION_LOG2 = 162;
	const NEWVERSION_ACACIA_WOODEN_STAIRS = 163;
	const NEWVERSION_DARK_OAK_WOODEN_STAIRS = 164;
	const NEWVERSION_SLIME_BLOCK = 165;
	const NEWVERSION_IRON_TRAPDOOR = 167;
	const NEWVERSION_PRISMARINE = 168;
	const NEWVERSION_SEA_LANTERN = 169;
	const NEWVERSION_HAY_BALE = 170;
	const NEWVERSION_CARPET = 171;
	const NEWVERSION_HARDENED_CLAY = 172;
	const NEWVERSION_COAL_BLOCK = 173;
	const NEWVERSION_PACKED_ICE = 174;
	const NEWVERSION_DOUBLE_PLANT = 175;
	const NEWVERSION_STANDING_BANNER = 176;
	const NEWVERSION_WALL_BANNER = 177;
	const NEWVERSION_INVERTED_DAYLIGHT_SENSOR = 178;
	const NEWVERSION_RED_SANDSTONE = 179;
	const NEWVERSION_RED_SANDSTONE_STAIRS = 180;
	const NEWVERSION_DOUBLE_RED_SANDSTONE_SLAB = 181;
	const NEWVERSION_RED_SANDSTONE_SLAB = 182;
	const NEWVERSION_FENCE_GATE_SPRUCE = 183;
	const NEWVERSION_FENCE_GATE_BIRCH = 184;
	const NEWVERSION_FENCE_GATE_JUNGLE = 185;
	const NEWVERSION_FENCE_GATE_DARK_OAK = 186;
	const NEWVERSION_FENCE_GATE_ACACIA = 187;
	const NEWVERSION_SPRUCE_DOOR_BLOCK = 193;
	const NEWVERSION_BIRCH_DOOR_BLOCK = 194;
	const NEWVERSION_JUNGLE_DOOR_BLOCK = 195;
	const NEWVERSION_ACACIA_DOOR_BLOCK = 196;
	const NEWVERSION_DARK_OAK_DOOR_BLOCK = 197;
	const NEWVERSION_GRASS_PATH = 198;
	const NEWVERSION_ITEM_FRAME_BLOCK = 199;
	const NEWVERSION_CHORUS_FLOWER = 200;
	const NEWVERSION_PURPUR_BLOCK = 201;
	const NEWVERSION_END_BRICKS = 206;
	const NEWVERSION_END_ROD = 208;
	const NEWVERSION_MAGMA = 213;
	const NEWVERSION_NETHER_WART_BLOCK_BLOCK = 214;
	const NEWVERSION_RED_NETHER_BRICK = 215;
	const NEWVERSION_BONE_BLOCK = 216;
	const NEWVERSION_SHULKER_BOX = 218;
	const NEWVERSION_CHORUS_PLANT = 240;
	const NEWVERSION_STAINED_GLASS = 241;
	const NEWVERSION_PODZOL = 243;
	const NEWVERSION_BEETROOT_BLOCK = 244;
	const NEWVERSION_STONECUTTER = 245;
	const NEWVERSION_GLOWING_OBSIDIAN = 246;
	const NEWVERSION_NETHER_REACTOR = 247;
	const NEWVERSION_IRON_SHOVEL = 296;
	const NEWVERSION_IRON_PICKAXE = 297;
	const NEWVERSION_IRON_AXE = 298;
	const NEWVERSION_FLINT_AND_STEEL = 299;
	const NEWVERSION_APPLE = 257;
	const NEWVERSION_BOW = 300;
	const NEWVERSION_ARROW = 301;
	const NEWVERSION_COAL = 302;
	const NEWVERSION_DIAMOND = 304;
	const NEWVERSION_IRON_INGOT = 305;
	const NEWVERSION_GOLD_INGOT = 306;
	const NEWVERSION_IRON_SWORD = 307;
	const NEWVERSION_WOODEN_SWORD = 308;
	const NEWVERSION_WOODEN_SHOVEL = 309;
	const NEWVERSION_WOODEN_PICKAXE = 310;
	const NEWVERSION_WOODEN_AXE = 311;
	const NEWVERSION_STONE_SWORD = 312;
	const NEWVERSION_STONE_SHOVEL = 313;
	const NEWVERSION_STONE_PICKAXE = 314;
	const NEWVERSION_STONE_AXE = 315;
	const NEWVERSION_DIAMOND_SWORD = 316;
	const NEWVERSION_DIAMOND_SHOVEL = 317;
	const NEWVERSION_DIAMOND_PICKAXE = 318;
	const NEWVERSION_DIAMOND_AXE = 319;
	const NEWVERSION_STICKS = 320;
	const NEWVERSION_BOWL = 321;
	const NEWVERSION_MUSHROOM_STEW = 260;
	const NEWVERSION_GOLDEN_SWORD = 322;
	const NEWVERSION_GOLDEN_SHOVEL = 323;
	const NEWVERSION_GOLDEN_PICKAXE = 324;
	const NEWVERSION_GOLDEN_AXE = 325;
	const WATER_BUCKET = 326;
	const LAVA_BUCKET = 327;
	const NEWVERSION_GUNPOWDER = 328;
	const NEWVERSION_WOODEN_HOE = 329;
	const NEWVERSION_STONE_HOE = 330;
	const NEWVERSION_IRON_HOE = 331;
	const NEWVERSION_DIAMOND_HOE = 332;
	const NEWVERSION_GOLDEN_HOE = 333;
	const NEWVERSION_WHEAT_SEEDS = 291;
	const NEWVERSION_WHEAT = 334;
	const NEWVERSION_BREAD = 261;
	const NEWVERSION_LEATHER_CAP = 335;
	const NEWVERSION_LEATHER_TUNIC = 336;
	const NEWVERSION_LEATHER_PANTS = 337;
	const NEWVERSION_LEATHER_BOOTS = 338;
	const NEWVERSION_CHAIN_HELMET = 339;
	const NEWVERSION_CHAIN_CHESTPLATE = 340;
	const NEWVERSION_CHAIN_LEGGINGS = 341;
	const NEWVERSION_CHAIN_BOOTS = 342;
	const NEWVERSION_IRON_HELMET = 343;
	const NEWVERSION_IRON_CHESTPLATE = 344;
	const NEWVERSION_IRON_LEGGINGS = 345;
	const NEWVERSION_IRON_BOOTS = 346;
	const NEWVERSION_DIAMOND_HELMET = 347;
	const NEWVERSION_DIAMOND_CHESTPLATE = 348;
	const NEWVERSION_DIAMOND_LEGGINGS = 349;
	const NEWVERSION_DIAMOND_BOOTS = 350;
	const NEWVERSION_GOLD_HELMET = 351;
	const NEWVERSION_GOLD_CHESTPLATE = 352;
	const NEWVERSION_GOLD_LEGGINGS = 353;
	const NEWVERSION_GOLD_BOOTS = 354;
	const NEWVERSION_FLINT = 356;
	const NEWVERSION_RAW_PORKCHOP = 262;
	const NEWVERSION_COOKED_PORKCHOP = 263;
	const NEWVERSION_SHIELD = 355;
	const NEWVERSION_PAINTING = 357;
	const NEWVERSION_GOLDEN_APPLE = 258;
	const NEWVERSION_WOODEN_DOOR = 359;
	const NEW_BUCKET = 360;
	const NEWVERSION_MINECART = 370;
	const NEWVERSION_SADDLE = 371;
	const NEWVERSION_IRON_DOOR = 372;
	const NEWVERSION_REDSTONE_DUST = 373;
	const NEWVERSION_SNOWBALL = 374;
	const NEWVERSION_BOAT = 626;
	const NEWVERSION_LEATHER = 381;
	const NEWVERSION_BRICK = 383;
	const NEWVERSION_CLAY = 384;
	const NEWVERSION_PAPER = 386;
	const NEWVERSION_BOOK = 387;
	const NEWVERSION_SLIMEBALL = 388;
	const NEWVERSION_MINECART_WITH_CHEST = 389;
	const NEWVERSION_EGG = 390;
	const NEWVERSION_COMPASS = 391;
	const NEWVERSION_FISHING_ROD = 392;
	const NEWVERSION_CLOCK = 393;
	const NEWVERSION_GLOWSTONE_DUST = 394;
	const NEWVERSION_DYE = 627;
	const NEWVERSION_BLACK_DYE = 395;
	const NEWVERSION_RED_DYE = 396;
	const NEWVERSION_GREEN_DYE = 397;
	const NEWVERSION_BROWN_DYE = 398;
	const NEWVERSION_BLUE_DYE = 399;
	const NEWVERSION_PURPLE_DYE = NEWVERSION;
	const NEWVERSION_CYAN_DYE = 401;
	const NEWVERSION_LIGHT_GRAY_DYE = 402;
	const NEWVERSION_GRAY_DYE = 403;
	const NEWVERSION_PINK_DYE = 404;
	const NEWVERSION_LIME_DYE = 405;
	const NEWVERSION_YELLOW_DYE = 406;
	const NEWVERSION_LIGHT_BLUE_DYE = 407;
	const NEWVERSION_MAGENTA_DYE = 408;
	const NEWVERSION_ORANGE_DYE = 409;
	const NEWVERSION_WHITE_DYE = 410;
	const NEWVERSION_BONE_MEAL = 411;
	const NEWVERSION_COCOA_BEANS = 412;
	const NEWVERSION_INC_SAC = 413;
	const NEWVERSION_LAPIS_LAZULI = 414;
	const NEWVERSION_BONE = 415;
	const NEWVERSION_SUGAR = 416;
	const NEWVERSION_CAKE = 417;
	const NEWVERSION_BED = 418;
	const NEWVERSION_REDSTONE_REPEATER = 419;
	const NEWVERSION_COOKIE = 271;
	const NEWVERSION_SHEARS = 421;
	const NEWVERSION_PUMPKIN_SEEDS = 292;
	const NEWVERSION_MELON_SEEDS = 293;
	const NEWVERSION_RAW_BEEF = 273;
	const NEWVERSION_COOKED_BEEF = 274;
	const NEWVERSION_RAW_CHICKEN = 275;
	const NEWVERSION_COOKED_CHICKEN = 276;
	const NEWVERSION_ROTTEN_FLESH = 277;
	const NEWVERSION_ENDER_PERL = 422;
	const NEWVERSION_BLAZE_ROD = 423;
	const NEWVERSION_GHAST_TEAR = 424;
	const NEWVERSION_GOLDEN_NUGGET = 425;
	const NEWVERSION_NETHER_WART = 294;
	const NEWVERSION_POTION = 426;
	const NEWVERSION_GLASS_BOTTLE = 427;
	const NEWVERSION_SPIDER_EYE = 278;
	const NEWVERSION_FERMENTED_SPIDER_EYE = 428;
	const NEWVERSION_BLAZE_POWDER = 429;
	const NEWVERSION_MAGMA_CREAM = 430;
	const NEWVERSION_BREWING_STAND = 431;
	const NEWVERSION_CAULDRON = 432;
	const NEWVERSION_EYE_OF_ENDER = 433;
	const NEWVERSION_SPAWN_EGG = 629;
	const NEWVERSION_BOTTLE_ENCHANTING = 508;
	const NEWVERSION_WRITABLE_BOOK = 510;
	const NEWVERSION_WRITTEN_BOOK = 511;
	const NEWVERSION_EMERALD = 512;
	const NEWVERSION_ITEM_FRAME = 513;
	const NEWVERSION_FLOWER_POT = 514;
	const NEWVERSION_CARROTS = 279;
	const NEWVERSION_POTATOES = 280;
	const NEWVERSION_BAKED_POTATOES = 281;
	const NEWVERSION_POISONOUS_POTATO = 282;
	const NEWVERSION_GOLDEN_CARROT = 283;
	const NEWVERSION_MOB_HEAD = 516;
	const NEWVERSION_PUMPKIN_PIE = 284;
	const NEWVERSION_ENCHANTING_BOOK = 521;
	const NEWVERSION_REDSTONE_COMPARATOR = 522;
	const NEWVERSION_NETHER_BRICK = 523;
	const NEWVERSION_NETHER_QUARTZ = 524;
	const NEWVERSION_MINECART_WITH_TNT = 525;
	const NEWVERSION_MINECART_WITH_HOPPER = 526;
	const NEWVERSION_PRISMARINE_SHARD = 565;
	const NEWVERSION_HOPPER = 527;
	const NEWVERSION_RAW_RABBIT = 288;
	const NEWVERSION_COOKED_RABBIT = 289;
	const NEWVERSION_RABBIT_STEW = 290;
	const NEWVERSION_RABBIT_FOOT = 528;
	const NEWVERSION_RABBIT_HIDE = 529;
	const NEWVERSION_LEAD = 547;
	const NEWVERSION_NAME_TAG = 548;
	const NEWVERSION_PRISMARINE_CRYSTAL = 549;
	const NEWVERSION_END_CRYSTAL = 630;
	const NEWVERSION_SPRUCE_DOOR = 553;
	const NEWVERSION_BIRCH_DOOR = 554;
	const NEWVERSION_JUNGLE_DOOR = 555;
	const NEWVERSION_ACACIA_DOOR = 556;
	const NEWVERSION_DARK_OAK_DOOR = 557;
	const NEWVERSION_CHORUS_FRUIT = 558;
	const NEWVERSION_DRAGONS_BREATH = 560;
	const NEWVERSION_SPLASH_POTION = 561;
	const NEWVERSION_LINGERING_POTION = 562;
	const NEWVERSION_ELYTRA = 564;
	const NEWVERSION_SHULKER_SHELL = 566;
	const NEWVERSION_IRON_NUGGET = 569;
	const NEWVERSION_BEETROOT = 285;
	const NEWVERSION_BEETROOT_SEED = 295;
	const NEWVERSION_BEETROOT_SOUP = 286;
	const NEWVERSION_RAW_SALMON = 265;
	const NEWVERSION_PUFFERFISH = 267;
	const NEWVERSION_COOKED_SALMON = 269;
	const NEWVERSION_CAMERA = 593;
	const NEWVERSION_AIR = 0;
	const NEWVERSION_SIGN = 358;
	const NEWVERSION_SUGAR_CANES = 83;
	const NEWVERSION_RAW_FISH = 264;
	const NEWVERSION_COOKED_FISH = 268;
	const NEWVERSION_MELON_SLICE = 272;
	const NEWVERSION_EMPTY_MAP = 515;
	const NEWVERSION_CARROT_ON_STICK = 517;
	const NEWVERSION_LEATHER_HORSE_ARMOR = 530;
	const NEWVERSION_IRON_HORSE_ARMOR = 531;
	const NEWVERSION_GOLDEN_HORSE_ARMOR = 532;
	const NEWVERSION_DIAMOND_HORSE_ARMOR = 533;
	const NEWVERSION_RAW_MUTTON = 550;
	const NEWVERSION_COOKED_MUTTON = 551;
	const NEWVERSION_CLOWNFISH = 266;
	const NEWVERSION_ENCHANTED_GOLDEN_APPLE = 259;
	const NEWVERSION_GLISTERING_MELON = 434;
	const NEWVERSION_OAK_WOOD_STAIRS = 53;
	const NEWVERSION_FILLED_MAP = 420;
	const NEWVERSION_NETHER_STAR = 518;
	const NEWVERSION_DISC_CHIRP = 537;
	const NEWVERSION_DISC_MALL = 539;
	const NEWVERSION_CHEST_MINECART = 389;
	const NEWVERSION_DISC_STRAD = 542;
	const NEWVERSION_DISC_WAIT = 545;
	const NEWVERSION_DISC_CAT = 535;
	const NEWVERSION_DISC_13 = 534;
	const NEWVERSION_DISC_MELLOHI = 540;
	const NEWVERSION_RECORD_MELLOHI = 540;
	const NEWVERSION_DISC_11 = 544;
	const NEWVERSION_FIRE_CHARGE = 509;
	const NEWVERSION_MILK_BUCKET = 361;
	const NEWVERSION_LAVA_BUCKET = 363;
	const NEWVERSION_COD_BUCKET = 364;
	const NEWVERSION_SALMON_BUCKET = 365;
	const NEWVERSION_TROPICAL_FISH_BUCKET = 366;
	const NEWVERSION_PUFFERFISH_BUCKET = 367;
	const NEWVERSION_COBBLESTONE = self::NEWVERSION_COBBLE;
	const NEWVERSION_PLANK = self::NEWVERSION_WOODEN_PLANKS;
	const NEWVERSION_SAPLING = self::NEWVERSION_SAPLINGS;
	const NEWVERSION_LOG = self::NEWVERSION_TRUNK;
	const NEWVERSION_LEAVES = self::NEWVERSION_LEAVE;
	const NEWVERSION_BUSH = self::NEWVERSION_DEAD_BUSH;
	const NEWVERSION_POPPY = self::NEWVERSION_RED_FLOWER;
	const NEWVERSION_DOUBLE_SLAB = self::NEWVERSION_DOUBLE_SLABS;
	const NEWVERSION_SLAB = self::NEWVERSION_SLABS;
	const NEWVERSION_BRICKS = self::NEWVERSION_BRICKS_BLOCK;
	const NEWVERSION_MOSS_STONE = self::NEWVERSION_MOSSY_STONE;
	const NEWVERSION_WOOD_STAIRS = self::NEWVERSION_OAK_WOODEN_STAIRS;
	const NEWVERSION_CRAFTING_TABLE = self::NEWVERSION_WORKBENCH;
	const NEWVERSION_BURNING_FURNACE = self::NEWVERSION_LIT_FURNACE;
	const NEWVERSION_WOODEN_DOOR_BLOCK = self::NEWVERSION_WOOD_DOOR_BLOCK;
	const NEWVERSION_DOOR_BLOCK = self::NEWVERSION_WOOD_DOOR_BLOCK;
	const NEWVERSION_COBBLE_STAIRS = self::NEWVERSION_COBBLESTONE_STAIRS;
	const NEWVERSION_GLOWING_REDSTONE_ORE = self::NEWVERSION_LIT_REDSTONE_ORE;
	const NEWVERSION_SNOW = self::NEWVERSION_SNOW_LAYER;
	const NEWVERSION_REEDS = self::NEWVERSION_SUGARCANE_BLOCK;
	const NEWVERSION_GLOWSTONE = self::NEWVERSION_GLOWSTONE_BLOCK;
	const NEWVERSION_LIT_PUMPKIN = self::NEWVERSION_JACK_O_LANTERN;
	const NEWVERSION_STONE_BRICKS = self::NEWVERSION_STONE_BRICK;
	const NEWVERSION_IRON_BAR = self::NEWVERSION_IRON_BARS;
	const NEWVERSION_GLASS_PANE = self::NEWVERSION_GLASS_PANEL;
	const NEWVERSION_VINE = self::NEWVERSION_VINES;
	const NEWVERSION_WATER_LILY = self::NEWVERSION_LILY_PAD;
	const NEWVERSION_NETHER_BRICKS = self::NEWVERSION_NETHER_BRICK_BLOCK;
	const NEWVERSION_ENCHANTING_TABLE = self::NEWVERSION_ENCHANTMENT_TABLE;
	const NEWVERSION_SPRUCE_WOOD_STAIRS = self::NEWVERSION_SPRUCE_WOODEN_STAIRS;
	const NEWVERSION_BIRCH_WOOD_STAIRS = self::NEWVERSION_BIRCH_WOODEN_STAIRS;
	const NEWVERSION_JUNGLE_WOOD_STAIRS = self::NEWVERSION_JUNGLE_WOODEN_STAIRS;
	const NEWVERSION_COBBLE_WALL = self::NEWVERSION_COBBLESTONE_WALL;
	const NEWVERSION_STONE_WALL = self::NEWVERSION_COBBLESTONE_WALL;
	const NEWVERSION_DOUBLE_WOOD_SLAB = self::NEWVERSION_DOUBLE_WOODEN_SLABS;
	const NEWVERSION_WOODEN_SLAB = self::NEWVERSION_WOODEN_SLABS;
	const NEWVERSION_WOOD_SLAB = self::NEWVERSION_WOODEN_SLABS;
	const NEWVERSION_STAINED_CLAY = self::NEWVERSION_STAINED_HARDENED_CLAY;
	const NEWVERSION_LEAVES2 = self::NEWVERSION_LEAVE2;
	const NEWVERSION_WOOD2 = self::NEWVERSION_LOG2;
	const NEWVERSION_TRUNK2 = self::NEWVERSION_LOG2;
	const NEWVERSION_ACACIA_WOOD_STAIRS = self::NEWVERSION_ACACIA_WOODEN_STAIRS;
	const NEWVERSION_DARK_OAK_WOOD_STAIRS = self::NEWVERSION_DARK_OAK_WOODEN_STAIRS;
	const NEWVERSION_DOUBLE_STONE_SLAB2 = self::NEWVERSION_DOUBLE_RED_SANDSTONE_SLAB;
	const NEWVERSION_STONE_SLAB2 = self::NEWVERSION_RED_SANDSTONE_SLAB;
	const NEWVERSION_FLINT_STEEL = self::NEWVERSION_FLINT_AND_STEEL;
	const NEWVERSION_STICK = self::NEWVERSION_STICKS;
	const NEWVERSION_GOLD_SWORD = self::NEWVERSION_GOLDEN_SWORD;
	const NEWVERSION_GOLD_SHOVEL = self::NEWVERSION_GOLDEN_SHOVEL;
	const NEWVERSION_GOLD_PICKAXE = self::NEWVERSION_GOLDEN_PICKAXE;
	const NEWVERSION_GOLD_AXE = self::NEWVERSION_GOLDEN_AXE;
	const NEWVERSION_GOLD_HOE = self::NEWVERSION_GOLDEN_HOE;
	const NEWVERSION_SEEDS = self::NEWVERSION_WHEAT_SEEDS;
	const NEWVERSION_REDSTONE = self::NEWVERSION_REDSTONE_DUST;
	const NEWVERSION_SUGARCANE = self::NEWVERSION_SUGAR_CANES;
	const NEWVERSION_MELON = self::NEWVERSION_MELON_SLICE;
	const NEWVERSION_STEAK = self::NEWVERSION_COOKED_BEEF;
	const NEWVERSION_GOLD_NUGGET = self::NEWVERSION_GOLDEN_NUGGET;
	const NEWVERSION_CARROT = self::NEWVERSION_CARROTS;
	const NEWVERSION_POTATO = self::NEWVERSION_POTATOES;
	const NEWVERSION_BAKED_POTATO = self::NEWVERSION_BAKED_POTATOES;
	const NEWVERSION_QUARTZ = self::NEWVERSION_NETHER_QUARTZ;
	const NEWVERSION_BEETROOT_SEEDS = self::NEWVERSION_BEETROOT_SEED;
	const NEWVERSION_ENCHANT_TABLE = self::NEWVERSION_ENCHANTING_TABLE;
	const NEWVERSION_WOODEN_PLANK = self::NEWVERSION_WOODEN_PLANKS;
	const NEWVERSION_WOOD = self::NEWVERSION_TRUNK;
	const NEWVERSION_WOODEN_STAIRS = self::NEWVERSION_WOOD_STAIRS;

	const DOUBLE_STONE_SLAB2 = 181;
	const STONE_SLAB2 = 182;
	const MAGMA = 213;
	const NETHER_WART_BLOCK_BLOCK = 214;
	// OLD
	const AIR = 0;
	const STONE = 1;
	const GRASS = 2;
	const DIRT = 3;
	const COBBLESTONE = 4;
	const COBBLE = 4;
	const PLANK = 5;
	const PLANKS = 5;
	const WOODEN_PLANK = 5;
	const WOODEN_PLANKS = 5;
	const SAPLING = 6;
	const SAPLINGS = 6;
	const BEDROCK = 7;
	const WATER = 8;
	const STILL_WATER = 9;
	const LAVA = 10;
	const STILL_LAVA = 11;
	const SAND = 12;
	const GRAVEL = 13;
	const GOLD_ORE = 14;
	const IRON_ORE = 15;
	const COAL_ORE = 16;
	const LOG = 17;
	const WOOD = 17;
	const TRUNK = 17;
	const LEAVES = 18;
	const LEAVE = 18;
	const SPONGE = 19;
	const GLASS = 20;
	const LAPIS_ORE = 21;
	const LAPIS_BLOCK = 22;
	const DISPENSER = 23;
	const BLACK_DYE = 393; //meta 16
 	const RED_DYE = 394; // meta 1
	const GREEN_DYE = 395; //  meta 2
	const BROWN_DYE = 396; //meta 17
	const BLUE_DYE = 397; // meta 18
	const PURPLE_DYE = 398; //meta 5
	const CYAN_DYE = 399; //meta 6
	const LIGHT_GRAY_DYE = 400; //meta 7
	const GRAY_DYE = 401; //meta 8
	const PINK_DYE = 402; // meta 9
	const LIME_DYE = 403; // meta 10
	const YELLOW_DYE = 404; // meta 11
	const LIGHT_BLUE_DYE = 405; // meta 12
	const MAGENTA_DYE = 406; // meta 13
	const ORANGE_DYE = 407; // meta 14
	const WHITE_DYE = 408; // meta 19
	const LAPIS_LAZULI = 412; // meta 4
	const SANDSTONE = 24;
	const NOTE_BLOCK = 25;
	const BED_BLOCK = 26;
	const POWERED_RAIL = 27;
	const DETECTOR_RAIL = 28;
	const STICKY_PISTON = 29;
	const COBWEB = 30;
	const TALL_GRASS = 31;
	const BUSH = 32;
	const DEAD_BUSH = 32;
	const PISTON = 33;
	const WOOL = 35;
	const DANDELION = 37;
	const POPPY = 38;
	const INC_SAC = 411; // meta 0
	const ROSE = 38;
	const RED_FLOWER = 38;
	const BROWN_MUSHROOM = 39;
	const RED_MUSHROOM = 40;
	const GOLD_BLOCK = 41;
	const IRON_BLOCK = 42;
	const DOUBLE_SLAB = 43;
	const DOUBLE_SLABS = 43;
	const SLAB = 44;
	const SLABS = 44;
	const BRICKS = 45;
	const BRICKS_BLOCK = 45;
	const TNT = 46;
	const BOOKSHELF = 47;
	const MOSS_STONE = 48;
	const MOSSY_STONE = 48;
	const OBSIDIAN = 49;
	const TORCH = 50;
	const FIRE = 51;
	const MONSTER_SPAWNER = 52;
	const WOOD_STAIRS = 53;
	const WOODEN_STAIRS = 53;
	const OAK_WOOD_STAIRS = 53;
	const OAK_WOODEN_STAIRS = 53;
	const CHEST = 54;
	const REDSTONE_WIRE = 55;
	const DIAMOND_ORE = 56;
	const DIAMOND_BLOCK = 57;
	const CRAFTING_TABLE = 58;
	const WORKBENCH = 58;
	const WHEAT_BLOCK = 59;
	const FARMLAND = 60;
	const FURNACE = 61;
	const BURNING_FURNACE = 62;
	const LIT_FURNACE = 62;
	const SIGN_POST = 63;
	const DOOR_BLOCK = 64;
	const WOODEN_DOOR_BLOCK = 64;
	const WOOD_DOOR_BLOCK = 64;
	const LADDER = 65;
	const RAIL = 66;
	const COBBLE_STAIRS = 67;
	const COBBLESTONE_STAIRS = 67;
	const WALL_SIGN = 68;
	const LEVER = 69;
	const STONE_PRESSURE_PLATE = 70;
	const IRON_DOOR_BLOCK = 71;
	const WOODEN_PRESSURE_PLATE = 72;
	const REDSTONE_ORE = 73;
	const GLOWING_REDSTONE_ORE = 74;
	const LIT_REDSTONE_ORE = 74;
	const REDSTONE_TORCH = 75;
	const REDSTONE_TORCH_ACTIVE = 76;
	const STONE_BUTTON = 77;
	const SNOW = 78;
	const SNOW_LAYER = 78;
	const ICE = 79;
	const SNOW_BLOCK = 80;
	const CACTUS = 81;
	const CLAY_BLOCK = 82;
	const REEDS = 83;
	const SUGARCANE_BLOCK = 83;
	const JUKEBOX = 84;
	const FENCE = 85;
	const PUMPKIN = 86;
	const NETHERRACK = 87;
	const SOUL_SAND = 88;
	const GLOWSTONE = 89;
	const GLOWSTONE_BLOCK = 89;
	const PORTAL = 90;
	const LIT_PUMPKIN = 91;
	const JACK_O_LANTERN = 91;
	const CAKE_BLOCK = 92;
	const REDSTONE_REPEATER_BLOCK = 93;
	const REDSTONE_REPEATER_BLOCK_ACTIVE = 94;
	const INVISIBLE_BEDROCK = 95;
	const TRAPDOOR = 96;
	const MONSTER_EGG = 97;
	const STONE_BRICKS = 98;
	const STONE_BRICK = 98;
	const BROWN_MUSHROOM_BLOCK = 99;
	CONST RED_MUSHROOM_BLOCK = 100;
	const IRON_BAR = 101;
	const IRON_BARS = 101;
	const GLASS_PANE = 102;
	const GLASS_PANEL = 102;
	const MELON_BLOCK = 103;
	const PUMPKIN_STEM = 104;
	const MELON_STEM = 105;
	const VINE = 106;
	const VINES = 106;
	const FENCE_GATE = 107;
	const BRICK_STAIRS = 108;
	const STONE_BRICK_STAIRS = 109;
	const MYCELIUM = 110;
	const WATER_LILY = 111;
	const LILY_PAD = 111;
	const NETHER_BRICKS = 112;
	const NETHER_BRICK_BLOCK = 112;
	const NETHER_BRICK_FENCE = 113;
	const NETHER_BRICKS_STAIRS = 114;
	const NETHER_WART_BLOCK = 115;
	const ENCHANTING_TABLE = 116;
	const ENCHANT_TABLE = 116;
	const ENCHANTMENT_TABLE = 116;
	const BREWING_STAND_BLOCK = 117;
	const CAULDRON_BLOCK = 118;
	const END_PORTAL = 120;
	const END_STONE = 121;
	const DRAGON_EGG = 122;
	const REDSTONE_LAMP = 123;
	const REDSTONE_LAMP_ACTIVE = 124;
	const DROPPER = 125;
	const ACTIVATOR_RAIL = 126;
	const COCOA = 127;
	const SANDSTONE_STAIRS = 128;
	const EMERALD_ORE = 129;
	const ENDER_CHEST = 130;
	const TRIPWIRE_HOOK = 131;
	const TRIPWIRE = 132;
	const EMERALD_BLOCK = 133;
	const SPRUCE_WOOD_STAIRS = 134;
	const SPRUCE_WOODEN_STAIRS = 134;
	const BIRCH_WOOD_STAIRS = 135;
	const BIRCH_WOODEN_STAIRS = 135;
	const JUNGLE_WOOD_STAIRS = 136;
	const JUNGLE_WOODEN_STAIRS = 136;
	const BEACON = 138;
	const COBBLE_WALL = 139;
	const STONE_WALL = 139;
	const COBBLESTONE_WALL = 139;
	const FLOWER_POT_BLOCK = 140;
	const CARROT_BLOCK = 141;
	const POTATO_BLOCK = 142;
	const WOODEN_BUTTON = 143;
	const MOB_HEAD_BLOCK = 144;
	const ANVIL = 145;
	const TRAPPED_CHEST = 146;
	const WEIGHTED_PRESSURE_PLATE_LIGHT = 147;
	const WEIGHTED_PRESSURE_PLATE_HEAVY = 148;
	const REDSTONE_COMPARATOR_BLOCK = 149;
	const REDSTONE_COMPARATOR_BLOCK_POWERED = 150;
	const DAYLIGHT_SENSOR = 151;
	const REDSTONE_BLOCK = 152;
	const NETHER_QUARTZ_ORE = 153;
	const HOPPER_BLOCK = 154;
	const QUARTZ_BLOCK = 155;
	const QUARTZ_STAIRS = 156;
	const DOUBLE_WOOD_SLAB = 157;
	const DOUBLE_WOODEN_SLAB = 157;
	const DOUBLE_WOOD_SLABS = 157;
	const DOUBLE_WOODEN_SLABS = 157;
	const WOOD_SLAB = 158;
	const WOODEN_SLAB = 158;
	const WOOD_SLABS = 158;
	const WOODEN_SLABS = 158;
	const STAINED_CLAY = 159;
	const STAINED_HARDENED_CLAY = 159;
	const STAINED_GLASS_PANE = 160;
	const LEAVES2 = 161;
	const LEAVE2 = 161;
	const WOOD2 = 162;
	const TRUNK2 = 162;
	const LOG2 = 162;
	const ACACIA_WOOD_STAIRS = 163;
	const ACACIA_WOODEN_STAIRS = 163;
	const DARK_OAK_WOOD_STAIRS = 164;
	const DARK_OAK_WOODEN_STAIRS = 164;
	const SLIME_BLOCK = 165;
	const IRON_TRAPDOOR = 167;
	const PRISMARINE = 168;
	const SEA_LANTERN = 169;
	const HAY_BALE = 170;
	const CARPET = 171;
	const HARDENED_CLAY = 172;
	const COAL_BLOCK = 173;
	const PACKED_ICE = 174;
	const DOUBLE_PLANT = 175;
	const STANDING_BANNER = 176;
	const WALL_BANNER = 177;
	const INVERTED_DAYLIGHT_SENSOR = 178;
	const RED_SANDSTONE = 179;
	const RED_SANDSTONE_STAIRS = 180;
	const DOUBLE_RED_SANDSTONE_SLAB = 181;
	const RED_SANDSTONE_SLAB = 182;
	const FENCE_GATE_SPRUCE = 183;
	const FENCE_GATE_BIRCH = 184;
	const FENCE_GATE_JUNGLE = 185;
	const FENCE_GATE_DARK_OAK = 186;
	const FENCE_GATE_ACACIA = 187;
	const SPRUCE_DOOR_BLOCK = 193;
	const BIRCH_DOOR_BLOCK = 194;
	const JUNGLE_DOOR_BLOCK = 195;
	const ACACIA_DOOR_BLOCK = 196;
	const DARK_OAK_DOOR_BLOCK = 197;
	const GRASS_PATH = 198;
	const ITEM_FRAME_BLOCK = 199;
	const CHORUS_FLOWER = 200;
	const PURPUR_BLOCK = 201;
	const END_BRICKS = 206;
	const END_ROD = 208;
	const RED_NETHER_BRICK = 215;
	const BONE_BLOCK = 216;
	const SHULKER_BOX = 218;
	const CHORUS_PLANT = 240;
	const STAINED_GLASS = 241;
	const PODZOL = 243;
	const BEETROOT_BLOCK = 244;
	const STONECUTTER = 245;
	const GLOWING_OBSIDIAN = 246;
	const NETHER_REACTOR = 247;
    const STRUCTURE_BLOCK = 252;

	//Normal Item IDs

	const IRON_SHOVEL = 256; //
	const IRON_PICKAXE = 257; //
	const IRON_AXE = 258; //
	const FLINT_STEEL = 259; //
	const FLINT_AND_STEEL = 259; //
	const APPLE = 260; //
	const BOW = 261;
	const ARROW = 262;
	const COAL = 263; //
	const DIAMOND = 264; //
	const IRON_INGOT = 265; //
	const GOLD_INGOT = 266; //
	const IRON_SWORD = 267;
	const WOODEN_SWORD = 268; //
	const WOODEN_SHOVEL = 269; //
	const WOODEN_PICKAXE = 270; //
	const WOODEN_AXE = 271; //
	const STONE_SWORD = 272;
	const STONE_SHOVEL = 273;
	const STONE_PICKAXE = 274;
	const STONE_AXE = 275;
	const DIAMOND_SWORD = 276;
	const DIAMOND_SHOVEL = 277;
	const DIAMOND_PICKAXE = 278;
	const DIAMOND_AXE = 279;
	const STICK = 280; //
	const STICKS = 280;
	const BOWL = 281; //
	const MUSHROOM_STEW = 282;
	const GOLD_SWORD = 283;
	const GOLD_SHOVEL = 284;
	const GOLD_PICKAXE = 285;
	const GOLD_AXE = 286;
	const GOLDEN_SWORD = 283;
	const GOLDEN_SHOVEL = 284;
	const GOLDEN_PICKAXE = 285;
	const GOLDEN_AXE = 286;
	const STRING = 287;
	const FEATHER = 288; //
	const GUNPOWDER = 289;
	const WOODEN_HOE = 290;
	const STONE_HOE = 291;
	const IRON_HOE = 292; //
	const DIAMOND_HOE = 293;
	const GOLD_HOE = 294;
	const GOLDEN_HOE = 294;
	const SEEDS = 295;
	const WHEAT_SEEDS = 295;
	const WHEAT = 296;
	const BREAD = 297;
	const LEATHER_CAP = 298;
	const LEATHER_TUNIC = 299;
	const LEATHER_PANTS = 300;
	const LEATHER_BOOTS = 301;
	const CHAIN_HELMET = 302;
	const CHAIN_CHESTPLATE = 303;
	const CHAIN_LEGGINGS = 304;
	const CHAIN_BOOTS = 305;
	const IRON_HELMET = 306;
	const IRON_CHESTPLATE = 307;
	const IRON_LEGGINGS = 308;
	const IRON_BOOTS = 309;
	const DIAMOND_HELMET = 310;
	const DIAMOND_CHESTPLATE = 311;
	const DIAMOND_LEGGINGS = 312;
	const DIAMOND_BOOTS = 313;
	const GOLD_HELMET = 314;
	const GOLD_CHESTPLATE = 315;
	const GOLD_LEGGINGS = 316;
	const GOLD_BOOTS = 317;
	const FLINT = 318;
	const RAW_PORKCHOP = 319;
	const COOKED_PORKCHOP = 320;
	const PAINTING = 321;
	const GOLDEN_APPLE = 322;
	const SIGN = 323;
	const WOODEN_DOOR = 324;
	const BUCKET = 325;
	const MINECART = 328;
	const SADDLE = 329;
	const IRON_DOOR = 330;
	const REDSTONE = 331;
	const REDSTONE_DUST = 331;
	const SNOWBALL = 332;
	const BOAT = 333;
	const LEATHER = 334;
	const BRICK = 336;
	const CLAY = 337;
	const SUGARCANE = 338;
	const SUGAR_CANE = 338;
	const SUGAR_CANES = 338;
	const PAPER = 339;
	const BOOK = 340;
	const SLIMEBALL = 341;
	const MINECART_WITH_CHEST = 342;
	const EGG = 344;
	const COMPASS = 345;
	const FISHING_ROD = 346;
	const CLOCK = 347;
	const GLOWSTONE_DUST = 348;
	const RAW_FISH = 349;
	const COOKED_FISH = 350;
	const DYE = 351;
	const BONE = 352;
	const SUGAR = 353;
	const CAKE = 354;
	const BED = 355;
	const REDSTONE_REPEATER = 356;
	const COOKIE = 357;
	const FILLED_MAP = 358;
	const SHEARS = 359;
	const MELON = 360;
	const MELON_SLICE = 360;
	const PUMPKIN_SEEDS = 361;
	const MELON_SEEDS = 362;
	const RAW_BEEF = 363;
	const STEAK = 364;
	const COOKED_BEEF = 364;
	const RAW_CHICKEN = 365;
	const COOKED_CHICKEN = 366;
	const ROTTEN_FLESH = 367;
	const ENDER_PEARL = 368;
	const BLAZE_ROD = 369;
	const GHAST_TEAR = 370;
	const GOLD_NUGGET = 371;
	const GOLDEN_NUGGET = 371;
	const NETHER_WART = 372;
	const POTION = 373;
	const GLASS_BOTTLE = 374;
	const SPIDER_EYE = 375;
	const FERMENTED_SPIDER_EYE = 376;
	const BLAZE_POWDER = 377;
	const MAGMA_CREAM = 378;
	const BREWING_STAND = 379;
	const CAULDRON = 380;
	const EYE_OF_ENDER = 381;
	const GLISTERING_MELON = 382;
	const SPAWN_EGG = 383;
	const BOTTLE_ENCHANTING = 384;
	const FIRE_CHARGE = 385;
	const WRITABLE_BOOK = 386;
	const WRITTEN_BOOK = 387;
	const EMERALD = 388;
	const ITEM_FRAME = 389;
	const FLOWER_POT = 390;
	const CARROT = 391;
	const CARROTS = 391;
	const POTATO = 392;
	const POTATOES = 392;
	const BAKED_POTATO = 393;
	const BAKED_POTATOES = 393;
	const POISONOUS_POTATO = 394;
	const EMPTY_MAP = 395;
	const GOLDEN_CARROT = 396;
	const MOB_HEAD = 397;
	const CARROT_ON_STICK = 398;
	const NETHER_STAR = 399;
	const PUMPKIN_PIE = 400;
	const ENCHANTING_BOOK = 403;
	const REDSTONE_COMPARATOR = 404;
	const NETHER_BRICK = 405;
	const QUARTZ = 406;
	const NETHER_QUARTZ = 406;
	const MINECART_WITH_TNT = 407;
	const MINECART_WITH_HOPPER = 408;
	const PRISMARINE_SHARD = 409;
	const HOPPER = 410;
	const RAW_RABBIT = 411;
	const COOKED_RABBIT = 412;
	const RABBIT_STEW = 413;
	const RABBIT_FOOT = 414;
	const RABBIT_HIDE = 415;
	const LEATHER_HORSE_ARMOR = 416;
	const IRON_HORSE_ARMOR = 417;
	const GOLDEN_HORSE_ARMOR = 418;
	const DIAMOND_HORSE_ARMOR = 419;
	const LEAD = 420;
	const NAME_TAG = 421;
	const PRISMARINE_CRYSTAL = 422;
	const RAW_MUTTON = 423;
	const COOKED_MUTTON = 424;
	const ENDER_CRYSTAL = 426;
	const SPRUCE_DOOR = 427;
	const BIRCH_DOOR = 428;
	const JUNGLE_DOOR = 429;
	const ACACIA_DOOR = 430;
	const DARK_OAK_DOOR = 431;
	const CHORUS_FRUIT = 432;
	const POPPED_CHORUS_FRUIT = 433;
	const DRAGONS_BREATH = 437;
	const SPLASH_POTION = 438;
	const LINGERING_POTION = 441;
	const ELYTRA = 444;
	const SHULKER_SHELL = 445;
	const TOTEM_OF_UNDYING = 450;
	const IRON_NUGGET = 452;
	const BEETROOT = 457;
	const BEETROOT_SEEDS = 458;
	const BEETROOT_SEED = 458;
	const BEETROOT_SOUP = 459;
	const RAW_SALMON = 460;
	const CLOWNFISH = 461;
	const PUFFERFISH = 462;
	const COOKED_SALMON = 463;
	const ENCHANTED_GOLDEN_APPLE = 466;
	const END_PEARL = 468;
	const CAMERA = 498;
	const RECORD_13 = 500;
	const RECORD_CAT = 501;
	const RECORD_BLOCKS = 502;
	const RECORD_CHIRP = 503;
	const RECORD_FAR = 504;
	const RECORD_MALL = 505;
	const RECORD_MELLOHI = 506;
	const RECORD_STAL = 507;
	const RECORD_STRAD = 508;
	const RECORD_WARD = 509;
	const RECORD_11 = 510;
	const RECORD_WAIT = 511;
	const SHIELD = 513;
	const FIREWORK = 401;
	protected static $names = [
		0 => "Air",
		1 => "Stone",
		2 => "Grass",
		3 => "Dirt",
		4 => "Cobblestone",
		5 => "Plank",
		6 => "Sapling",
		7 => "Bedrock",
		8 => "Water",
		9 => "Still Water",
		10 => "Lava",
		11 => "Still Lava",
		12 => "Sand",
		13 => "Gravel",
		14 => "Gold Ore",
		15 => "Iron Ore",
		16 => "Coal Ore",
		17 => "Wood",
		18 => "Leaves",
		19 => "Sponge",
		20 => "Glass",
		21 => "Lapis Ore",
		22 => "Lapis Block",
		24 => "Sandstone",
		26 => "Bed",
		30 => "Cobweb",
		31 => "Tall Grass",
		32 => "Bush",
		35 => "Wool",
		37 => "Dandelion",
		38 => "Red Flower",
		39 => "Brown Mushroom",
		40 => "Red Mushroom",
		41 => "Gold Block",
		42 => "Iron Block",
		43 => "Double Slab",
		44 => "Slab",
		45 => "Bricks",
		46 => "TNT",
		47 => "Bookshelf",
		48 => "Moss Stone",
		49 => "Obsidian",
		50 => "Torch",
		51 => "Fire",
		52 => "Monster Spawner",
		53 => "Wooden Stairs",
		54 => "Chest",
		56 => "Diamond Ore",
		57 => "Diamond Block",
		58 => "Crafting Table",
		59 => "Wheat Block",
		60 => "Farmland",
		61 => "Furnace",
		62 => "Burning Furnace",
		63 => "Sign Post",
		64 => "Door",
		65 => "Ladder",
		66 => "Rail",
		67 => "Cobble Stairs",
		68 => "Wall Sign",
		71 => "Iron Door",
		73 => "Redstone Ore",
		74 => "Glowing Redstone Ore",
		75 => "Redstone Torch",
		76 => "Glowing Redstone Torch",
		78 => "Snow",
		79 => "Ice",
		80 => "Snow Block",
		81 => "Cactus",
		82 => "Clay Block",
		83 => "Sugarcane Block",
		85 => "Fence",
		86 => "Pumpkin Block",
		87 => "Netherrack",
		88 => "Soul Sand",
		89 => "Glowstone",
		90 => "Portal",
		91 => "Jack-O'-Lantern",
		92 => "Cake Block",
		96 => "Trapdoor",
		98 => "Stone Bricks",
		99 => "Brown Mushroom Block",
		100 => "Red Mushroom Block",
		101 => "Iron Bar",
		102 => "Glass Panel",
		103 => "Melon BLock",
		104 => "Pumpkin Stem",
		106 => "Vine",
		107 => "Fence Gate",
		108 => "Brick Stairs",
		109 => "Stone Brick Stairs",
		110 => "Mycelium",
		111 => "Water Lily",
		112 => "Nether Brick",
		113 => "Nether Brick Fence",
		114 => "Nether Brick Stairs",
		116 => "Enchantment Table",
		117 => "Brewing Stand",
		118 => "Cauldron Block",
		120 => "End Portal",
		121 => "End Stone",
        self::DRAGON_EGG => 'Dragon Egg',
		123 => "Redstone Lamp",
		124 => "Redstone Lamp Active",
		125 => "Dropper",
		126 => "Activator Rail",
		127 => "Cocoa",
		128 => "Sendstone Stairs",
		129 => "Emerald Ore",
        self::ENDER_CHEST => 'Ender Chest',
		self::ENDER_PEARL => 'EnderPearl',
		131 => "Tripwire Hook",
		132 => "Tripwire",
		133 => "Emerald Block",
		134 => "Spruce Wood Stairs",
		135 => "Birch Wood Stairs",
		136 => "Jungle Wood Stairs",
		138 => "Beacon",
		139 => "Cobblestone Wall",
		140 => "Flower Pot",
		141 => "Carrot Block",
		142 => "Potato Block",
		143 => "Wooden Button",
		144 => "Mob Head",
		145 => "Anvil",
		146 => "Trapped Chest",
		147 => "Weighted Pressure Plate Light",
		148 => "Weighted Pressure Plate Heavy",
		149 => "Redstone Comparator",
		150 => "Redstone Comparator Powered",
		151 => "Daylight Sensor",
		152 => "Redstone Block",
		153 => "Nether Quartz Ore",
		154 => "Hopper",
		155 => "Quartz Block",
		156 => "Quartz Stairs",
		157 => "Double Wood Slab",
		158 => "Wooden Slab",
		159 => "Stained Clay",
        self::STAINED_GLASS_PANE => 'Stained Glass Pane',
		161 => "Leaves2",
		162 => "Wood2",
		163 => "Acacia Wood Stairs",
		164 => "Dark Oak Wood Stairs",
		165 => "Slime Block",
		167 => "Iron Trapdoor",
		170 => "Hay Bale",
		171 => "Carpet",
		172 => "Hardened CLay",
		173 => "Coal BLock",
		175 => "Double Plant",
		178 => "Inverted Daylight Sensor",
		179 => "Red Sandstone",
		180 => "Red Sandstone Stairs",
		181 => "Double Red Sandstone Slab",
		182 => "Red Sandstone Slab",
		183 => "Fence Gate Spruce",
		184 => "Fence Gate Birch",
		185 => "Fence Gate Jungle",
		186 => "Fence Gate Dark Oak",
		187 => "Fence Gate Acacia",
		193 => "Wood Door Block",
		194 => "Birch Door",
		195 => "Jungle Door",
		196 => "Acacia Door",
		197 => "Dark Oak Door",
		198 => "Grass Path",
		218 => "Shulker Box",
        self::CHORUS_FLOWER => 'Chorus Flower',
        self::PURPUR_BLOCK => 'Purpur Block',
        self::END_BRICKS => 'End Brick',
        self::END_ROD => 'End Rod',
        self::CHORUS_PLANT => 'Chorus Plant',
        self::STAINED_GLASS => 'Stained Glass',
		243 => "Podzol",
		244 => "Beetroot Block",
		245 => "Stonecutter",
		246 => "Glowing Obsidian",
		247 => "Nether Reactor",
		252 => "Structure Block",
		256 => "Iron Shovel",
		257 => "Iron Pickaxe",
		258 => "Iron Axe",
		259 => "Flint and Steel",
		260 => "Apple",
		261 => "Bow",
		262 => "Arrow",
		263 => "Coal",
		264 => "Diamond",
		265 => "Iron Ingot",
		266 => "Gold Ingot",
		267 => "Iron Sword",
		268 => "Wooden Sword",
		269 => "Wooden Shovel",
		270 => "Wooden Pickaxe",
		271 => "Wooden Axe",
		272 => "Stone Sword",
		273 => "Stone Shovel",
		274 => "Stone Pickaxe",
		275 => "Stone Axe",
		276 => "Diamond Sword",
		277 => "Diamond Shovel",
		278 => "Diamond Pickaxe",
		279 => "Diamond Axe",
		280 => "Stick",
		281 => "Bowl",
		282 => "Mushroom Stew",
		283 => "Gold Sword",
		284 => "Gold Shovel",
		285 => "Gold Pickaxe",
		286 => "Gold Axe",
		287 => "String",
		288 => "Feather",
		289 => "Gunpowder",
		290 => "Wooden Hoe",
		291 => "Stone Hoe",
		292 => "Iron Hoe",
		293 => "Diamond Hoe",
		294 => "Gold Hoe",
		295 => "Wheat Seed",
		296 => "Wheat",
		297 => "Bread",
		298 => "Leather Cap",
		299 => "Leather Tunic",
		300 => "Leather Pants",
		301 => "Leather Boots",
		302 => "Chain Helmet",
		303 => "Chain Chestplate",
		304 => "Chain Leggins",
		305 => "Chain Boots",
		306 => "Iron Helmet",
		307 => "Iron Chestplate",
		308 => "Iron Leggins",
		309 => "Iron Boots",
		310 => "Diamond Helmet",
		311 => "Diamond Chestplate",
		312 => "Diamond Leggins",
		313 => "Diamond Boots",
		314 => "Gold Helmet",
		315 => "Gold Chestplate",
		316 => "Gold Leggins",
		317 => "Gold Boots",
		318 => "Flint",
		319 => "Raw Porkchop",
		320 => "Cooked Porkchop",
		321 => "Painting",
		322 => "Golden Apple",
		323 => "Sign",
		324 => "Wooden Door",
		325 => "Bucket",
		326 => "Water Bucket",
		328 => "Minecart",
		330 => "Iron Door",
		331 => "Redstone",
		332 => "Snowball",
		334 => "Leather",
		336 => "Bricks",
		337 => "Clay",
		338 => "Sugarcane",
		339 => "Paper",
		340 => "Book",
		341 => "Slimeball",
		344 => "Egg",
		345 => "Compass",
		346 => "Compass",
		347 => "Clock",
		348 => "Glowstone Dust",
		349 => "Raw Fish",
		350 => "Cooked Fish",
		351 => "Dye",
		352 => "Bone",
		353 => "Sugar",
		354 => "Cake",
		355 => "Bed",
		357 => "Cookie",
		358 => "Filled Map",
		359 => "Shears",
		360 => "Melon",
		361 => "Pumpkin Seed",
		362 => "Melon Seed",
		363 => "Raw Beef",
		364 => "Steak",
		365 => "Raw Chicken",
		366 => "Cooked Chicken",
		369 => "Blaze Rod",
		371 => "Gold Nugget",
		373 => "Potion",
		377 => "Blaze powder",
		378 => "Magma Cream",
		383 => "Spawn Egg",
		385 => "Fire Charge",
		self::WRITABLE_BOOK => "Book & Quill",
		self::WRITTEN_BOOK => "Written Book",
		388 => "Emerald",
		389 => "Item Frame",
		390 => "Flower Pot",
		391 => "Carrot",
		392 => "Potato",
		393 => "Baked Potato",
		394 => "Poisonous Potato",
		395 => "Empty Map",
		396 => "Golden Carrot",
		397 => "Mob Head",
		398 => "Carrot on a Stick",
		400 => "Pumpkin Pie",
		403 => "Enchanted Book",
		404 => "Redstone Comparator",
		405 => "Nether Bricks",
		406 => "Quartz",
		407 => "Minecart with TNT",
		408 => "Minecart with Hopper",
		410 => "Hopper",
		411 => "Raw Rabbit",
		412 => "Cooked Rabbit",
		414 => "Rabbit's Foot",
		415 => "Rabbit Hide",
		416 => "Leather Horse Armor",
		417 => "Iron Horse Armor",
		418 => "Golden Horse Armor",
		419 => "Diamond Horse Armor",
		420 => "Lead",
		421 => "Name Tag",
		self::PRISMARINE_CRYSTAL => "Prismarine Crystal",
		423 => "Raw Mutton",
		424 => "Cooked Mutton",
		426 => "Ender Crystal",
		427 => "Spruce Door",
		428 => "Birch Door",
		429 => "Jungle Door",
		430 => "Acacia Door",
		431 => "Dark Oak Door",
		431 => "Chorus Fruit",
		438 => "Splash Potion",
		457 => "Beetroot",
		458 => "Beetroot Seed",
		459 => "Beetroot Soup",
		460 => "Raw Salmon",
		461 => "Clownfish",
		462 => "Pufferfish",
		463 => "Cooked Salmon",
		466 => "Enchanted Golden Apple",
		498 => "Camera",
		500 => "Record_13",
		501 => "Record_cat",
		502 => "Record_blocks",
		503 => "Record_chirp",
		504 => "Record_far",
		505 => "Record_mall",
		506 => "Record_mellohi",
		507 => "Record_stal",
		508 => "Record_strad",
		509 => "Record_ward",
		510 => "Record_11",
		511 => "Record_wait",
		513 => "Shield",
		401 => "Fireworks",
	];
	/** @var \SplFixedArray */
	public static $list = null;
	public static $listNew = null;
	public static $food = null;
	protected $block;
	protected $id;
	protected $meta;
	public $tags = "";
	private $cachedNBT = null;
	public $count;
	protected $durability = 0;
	protected $name;
	protected $obtainTime = 0;
	protected $canPlaceOnBlocks = [];
	protected $canDestroyBlocks = [];

	public function canBeActivated(){
		return false;
	}
    public function hasCompoundTag() : bool{
        return $this->tags !== "";
    }
	public static function init(){
		if(self::$list === null){
			self::$list = new \SplFixedArray(65536);
			self::$listNew = new \SplFixedArray(65536);
      self::$list[self::ENDER_CRYSTAL] = EnderCrystal::class;
      self::$list[self::SHULKER_BOX] = ShulkerBox::class;
      self::$list[self::FIRE_CHARGE] = FireCharge::class;
      self::$list[self::FIREWORK] = Firework::class;
      self::$list[self::STRUCTURE_BLOCK] = StructureBlock::class;
      self::$list[self::CAULDRON] = Cauldron::class;
      self::$list[self::HOPPER] = Hopper::class;
			self::$list[self::SUGARCANE] = Sugarcane::class;
			self::$list[self::WHEAT_SEEDS] = WheatSeeds::class;
			self::$list[self::PUMPKIN_SEEDS] = PumpkinSeeds::class;
			self::$list[self::MELON_SEEDS] = MelonSeeds::class;
			self::$list[self::MUSHROOM_STEW] = MushroomStew::class;
			self::$list[self::BEETROOT_SOUP] = BeetrootSoup::class;
			self::$list[self::CARROT] = Carrot::class;
			self::$list[self::POTATO] = Potato::class;
			self::$list[self::BEETROOT_SEEDS] = BeetrootSeeds::class;
			self::$list[self::SIGN] = Sign::class;
			self::$list[self::WOODEN_DOOR] = WoodenDoor::class;
			self::$list[self::MINECART] = Minecart::class;
			self::$list[self::BOAT] = Boat::class;
			self::$list[self::FISHING_ROD] = FishingRod::class;
			self::$list[self::BUCKET] = Bucket::class;
			self::$list[self::WATER_BUCKET] = WaterBucket::class;
			self::$list[self::LAVA_BUCKET] = LavaBucket::class;
			self::$list[self::IRON_DOOR] = IronDoor::class;
			self::$list[self::CAKE] = Cake::class;
			self::$list[self::BED] = Bed::class;
			self::$list[self::PAINTING] = Painting::class;
			self::$list[self::COAL] = Coal::class;
			self::$list[self::APPLE] = Apple::class;
			self::$list[self::SPAWN_EGG] = SpawnEgg::class;
			self::$list[self::DIAMOND] = Diamond::class;
			self::$list[self::STICK] = Stick::class;
			self::$list[self::SNOWBALL] = Snowball::class;
			self::$list[self::EGG] = Egg::class;
			self::$list[self::BOWL] = Bowl::class;
			self::$list[self::FEATHER] = Feather::class;
			self::$list[self::BRICK] = Brick::class;
			self::$list[self::LEATHER_CAP] = LeatherCap::class;
			self::$list[self::LEATHER_TUNIC] = LeatherTunic::class;
			self::$list[self::LEATHER_PANTS] = LeatherPants::class;
			self::$list[self::LEATHER_BOOTS] = LeatherBoots::class;
			self::$list[self::CHAIN_HELMET] = ChainHelmet::class;
			self::$list[self::CHAIN_CHESTPLATE] = ChainChestplate::class;
			self::$list[self::CHAIN_LEGGINGS] = ChainLeggings::class;
			self::$list[self::CHAIN_BOOTS] = ChainBoots::class;
			self::$list[self::IRON_HELMET] = IronHelmet::class;
			self::$list[self::IRON_CHESTPLATE] = IronChestplate::class;
			self::$list[self::IRON_LEGGINGS] = IronLeggings::class;
			self::$list[self::IRON_BOOTS] = IronBoots::class;
			self::$list[self::GOLD_HELMET] = GoldHelmet::class;
			self::$list[self::GOLD_CHESTPLATE] = GoldChestplate::class;
			self::$list[self::GOLD_LEGGINGS] = GoldLeggings::class;
			self::$list[self::GOLD_BOOTS] = GoldBoots::class;
			self::$list[self::DIAMOND_HELMET] = DiamondHelmet::class;
			self::$list[self::DIAMOND_CHESTPLATE] = DiamondChestplate::class;
			self::$list[self::DIAMOND_LEGGINGS] = DiamondLeggings::class;
			self::$list[self::DIAMOND_BOOTS] = DiamondBoots::class;
			self::$list[self::IRON_SWORD] = IronSword::class;
			self::$list[self::IRON_INGOT] = IronIngot::class;
			self::$list[self::GOLD_INGOT] = GoldIngot::class;
			self::$list[self::IRON_SHOVEL] = IronShovel::class;
			self::$list[self::IRON_PICKAXE] = IronPickaxe::class;
			self::$list[self::IRON_AXE] = IronAxe::class;
			self::$list[self::IRON_HOE] = IronHoe::class;
			self::$list[self::DIAMOND_SWORD] = DiamondSword::class;
			self::$list[self::DIAMOND_SHOVEL] = DiamondShovel::class;
			self::$list[self::DIAMOND_PICKAXE] = DiamondPickaxe::class;
			self::$list[self::DIAMOND_AXE] = DiamondAxe::class;
			self::$list[self::DIAMOND_HOE] = DiamondHoe::class;
			self::$list[self::GOLD_SWORD] = GoldSword::class;
			self::$list[self::GOLD_SHOVEL] = GoldShovel::class;
			self::$list[self::GOLD_PICKAXE] = GoldPickaxe::class;
			self::$list[self::GOLD_AXE] = GoldAxe::class;
			self::$list[self::GOLD_HOE] = GoldHoe::class;
			self::$list[self::STONE_SWORD] = StoneSword::class;
			self::$list[self::STONE_SHOVEL] = StoneShovel::class;
			self::$list[self::STONE_PICKAXE] = StonePickaxe::class;
			self::$list[self::STONE_AXE] = StoneAxe::class;
			self::$list[self::STONE_HOE] = StoneHoe::class;
			self::$list[self::WOODEN_SWORD] = WoodenSword::class;
			self::$list[self::WOODEN_SHOVEL] = WoodenShovel::class;
			self::$list[self::WOODEN_PICKAXE] = WoodenPickaxe::class;
			self::$list[self::WOODEN_AXE] = WoodenAxe::class;
			self::$list[self::WOODEN_HOE] = WoodenHoe::class;
			self::$list[self::FLINT_STEEL] = FlintSteel::class;
			self::$list[self::SHEARS] = Shears::class;
			self::$list[self::BOW] = Bow::class;
			self::$list[self::RAW_FISH] = Fish::class;
			self::$list[self::COOKED_FISH] = CookedFish::class;
			self::$list[self::MOB_HEAD] = MobHead::class;
			self::$list[self::BLAZE_POWDER] = BlazePowder::class;
			self::$list[self::FLOWER_POT] = FlowerPot::class;
			self::$list[self::ELYTRA] = Elytra::class;
			self::$list[self::PRISMARINE_CRYSTAL] = PrismarineCrystal::class;
			self::$list[self::POTION] = Potion::class;
			self::$list[self::REDSTONE_REPEATER] = Repeater::class;
			self::$list[self::BOTTLE_ENCHANTING] = BottleOEnchanting::class;
			self::$list[self::WRITABLE_BOOK] = WritableBook::class;

			self::$list[self::ENDER_PEARL] = EnderPearl::class;

			self::$list[self::SPRUCE_DOOR] = SpruceDoor::class;
			self::$list[self::BIRCH_DOOR] = BirchDoor::class;
			self::$list[self::JUNGLE_DOOR] = JungleDoor::class;
			self::$list[self::ACACIA_DOOR] = AcaciaDoor::class;
			self::$list[self::DARK_OAK_DOOR] = DarkOakDoor::class;
			self::$list[self::SPLASH_POTION] = SplashPotion::class;
			self::$list[self::CHORUS_FRUIT] = ChorusFruit::class;
			self::$list[self::REDSTONE_DUST] = Redstone::class;
			self::$list[self::TOTEM_OF_UNDYING] = TotemOfUndying::class;
			self::$list[self::ITEM_FRAME] = ItemFrame::class;
		}

		self::initCreativeItems();
		self::initFood();
	}

	public static function registerItem($id, $class) {
		if (isset(self::$list[$id]) && self::$list[$id] == $class) {
			return;
		}
		self::$list[$id] = $class;
		foreach (self::$creative as $index => $itemData) {
			$item = $itemData['item'];
			if ($item->getId() == $id) {
				self::$creative[$index] = ['item' => Item::get($id, $item->getDamage()), 'group' => self::CREATIVE_GROUP_NONE];
			}
		}
	}

	public function pop(int $count = 1) : Item{
		if($count > $this->count){
			throw new InvalidArgumentException("Cannot pop $count items from a stack of $this->count");
		}

		$item = clone $this;
		$item->count = $count;

		$this->count -= $count;

		return $item;
	}

	private static $creative = [];
	private static $creative110 = [];

	private static function initCreativeItems(){
		self::clearCreativeItems();

		self::addCreativeItem(Item::get(Item::WOODEN_PLANKS, 0), self::CREATIVE_GROUP_PLANKS);
		self::addCreativeItem(Item::get(Item::WOODEN_PLANKS, 1), self::CREATIVE_GROUP_PLANKS);
		self::addCreativeItem(Item::get(Item::WOODEN_PLANKS, 2), self::CREATIVE_GROUP_PLANKS);
		self::addCreativeItem(Item::get(Item::WOODEN_PLANKS, 3), self::CREATIVE_GROUP_PLANKS);
		self::addCreativeItem(Item::get(Item::WOODEN_PLANKS, 4), self::CREATIVE_GROUP_PLANKS);
		self::addCreativeItem(Item::get(Item::WOODEN_PLANKS, 5), self::CREATIVE_GROUP_PLANKS);

		self::addCreativeItem(Item::get(Item::COBBLESTONE_WALL, 0), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::COBBLESTONE_WALL, 1), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 2), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 3), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 4), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 5), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 6), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 7), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 8), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 9), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 10), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 11), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 12), self::CREATIVE_GROUP_WALLS);
		self::addCreativeItem(Item::get(Item::STONE_WALL, 13), self::CREATIVE_GROUP_WALLS);

		self::addCreativeItem(Item::get(Item::FENCE, 0), self::CREATIVE_GROUP_FENCE);
		self::addCreativeItem(Item::get(Item::FENCE, 1), self::CREATIVE_GROUP_FENCE);
		self::addCreativeItem(Item::get(Item::FENCE, 2), self::CREATIVE_GROUP_FENCE);
		self::addCreativeItem(Item::get(Item::FENCE, 3), self::CREATIVE_GROUP_FENCE);
		self::addCreativeItem(Item::get(Item::FENCE, 4), self::CREATIVE_GROUP_FENCE);
		self::addCreativeItem(Item::get(Item::FENCE, 5), self::CREATIVE_GROUP_FENCE);
		self::addCreativeItem(Item::get(Item::NETHER_BRICK_FENCE, 0), self::CREATIVE_GROUP_FENCE);

		self::addCreativeItem(Item::get(Item::FENCE_GATE, 0), self::CREATIVE_GROUP_FENCEGATE);
		self::addCreativeItem(Item::get(Item::FENCE_GATE_SPRUCE, 0), self::CREATIVE_GROUP_FENCEGATE);
		self::addCreativeItem(Item::get(Item::FENCE_GATE_BIRCH, 0), self::CREATIVE_GROUP_FENCEGATE);
		self::addCreativeItem(Item::get(Item::FENCE_GATE_DARK_OAK, 0), self::CREATIVE_GROUP_FENCEGATE);
		self::addCreativeItem(Item::get(Item::FENCE_GATE_JUNGLE, 0), self::CREATIVE_GROUP_FENCEGATE);
		self::addCreativeItem(Item::get(Item::FENCE_GATE_ACACIA, 0), self::CREATIVE_GROUP_FENCEGATE);

		self::addCreativeItem(Item::get(Item::COBBLESTONE_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::OAK_WOODEN_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::SPRUCE_WOODEN_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::BIRCH_WOODEN_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::JUNGLE_WOODEN_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::ACACIA_WOODEN_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::DARK_OAK_WOODEN_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::BRICK_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::STONE_BRICK_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::NETHER_BRICKS_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::SANDSTONE_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::QUARTZ_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);
		self::addCreativeItem(Item::get(Item::RED_SANDSTONE_STAIRS, 0), self::CREATIVE_GROUP_STAIRS);

		self::addCreativeItem(Item::get(Item::WOODEN_DOOR, 0), self::CREATIVE_GROUP_DOOR);

		self::addCreativeItem(Item::get(Item::TRAPDOOR, 0), self::CREATIVE_GROUP_TRAPDOOR);

		self::addCreativeItem(Item::get(Item::GLASS, 0), self::CREATIVE_GROUP_GLASS);
		self::addColoredCreativeItem(self::STAINED_GLASS, self::CREATIVE_GROUP_GLASS);

		self::addCreativeItem(Item::get(Item::GLASS_PANE, 0), self::CREATIVE_GROUP_GLASSPANE);
		self::addColoredCreativeItem(self::STAINED_GLASS_PANE, self::CREATIVE_GROUP_GLASSPANE);

		self::addCreativeItem(Item::get(Item::SLAB, 0), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::SLAB, 3), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::WOODEN_SLAB, 0), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::WOODEN_SLAB, 1), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::WOODEN_SLAB, 2), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::WOODEN_SLAB, 3), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::WOODEN_SLAB, 4), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::WOODEN_SLAB, 5), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::SLAB, 4), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::SLAB, 5), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::SLAB, 6), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::SLAB, 1), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::SLAB, 7), self::CREATIVE_GROUP_SLAB);

		self::addCreativeItem(Item::get(Item::STONE_SLAB2, 0), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::STONE_SLAB2, 1), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::STONE_SLAB2, 2), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::STONE_SLAB2, 3), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::STONE_SLAB2, 4), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::STONE_SLAB2, 5), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::STONE_SLAB2, 6), self::CREATIVE_GROUP_SLAB);
		self::addCreativeItem(Item::get(Item::STONE_SLAB2, 7), self::CREATIVE_GROUP_SLAB);

		self::addCreativeItem(Item::get(Item::BUCKET, 0));
		self::addCreativeItem110(Item::get(Item::BUCKET, 1));
		self::addCreativeItem110(Item::get(Item::BUCKET, 8));
		self::addCreativeItem110(Item::get(Item::BUCKET, 10));
		self::addCreativeItem(Item::get(Item::WATER_BUCKET, 0));
		self::addCreativeItem(Item::get(Item::LAVA_BUCKET, 0));

		self::addCreativeItem(Item::get(Item::STONE_BRICKS, 0), self::CREATIVE_GROUP_STONEBRICK);
		self::addCreativeItem(Item::get(Item::STONE_BRICKS, 1), self::CREATIVE_GROUP_STONEBRICK);
		self::addCreativeItem(Item::get(Item::STONE_BRICKS, 2), self::CREATIVE_GROUP_STONEBRICK);
		self::addCreativeItem(Item::get(Item::STONE_BRICKS, 3), self::CREATIVE_GROUP_STONEBRICK);
		self::addCreativeItem(Item::get(Item::END_BRICKS, 0), self::CREATIVE_GROUP_STONEBRICK);

		self::addCreativeItem(Item::get(Item::SANDSTONE, 0), self::CREATIVE_GROUP_SANDSTONE);
		self::addCreativeItem(Item::get(Item::SANDSTONE, 1), self::CREATIVE_GROUP_SANDSTONE);
		self::addCreativeItem(Item::get(Item::SANDSTONE, 2), self::CREATIVE_GROUP_SANDSTONE);

		self::addColoredCreativeItem(Item::WOOL, self::CREATIVE_GROUP_WOOL);
		self::addColoredCreativeItem(Item::CARPET, self::CREATIVE_GROUP_WOOLCARPET);

		self::addCreativeItem(Item::get(Item::CLAY_BLOCK, 0), self::CREATIVE_GROUP_STAINEDCLAY);
		self::addCreativeItem(Item::get(Item::HARDENED_CLAY, 0), self::CREATIVE_GROUP_STAINEDCLAY);
		self::addColoredCreativeItem(Item::STAINED_CLAY, self::CREATIVE_GROUP_STAINEDCLAY);

		self::addCreativeItem(Item::get(Item::STONE, 0), self::CREATIVE_GROUP_STONE);
		self::addCreativeItem(Item::get(Item::STONE, 1), self::CREATIVE_GROUP_STONE);
		self::addCreativeItem(Item::get(Item::STONE, 2), self::CREATIVE_GROUP_STONE);
		self::addCreativeItem(Item::get(Item::STONE, 3), self::CREATIVE_GROUP_STONE);
		self::addCreativeItem(Item::get(Item::STONE, 4), self::CREATIVE_GROUP_STONE);
		self::addCreativeItem(Item::get(Item::STONE, 5), self::CREATIVE_GROUP_STONE);
		self::addCreativeItem(Item::get(Item::STONE, 6), self::CREATIVE_GROUP_STONE);

		self::addCreativeItem(Item::get(Item::IRON_ORE, 0), self::CREATIVE_GROUP_ORE);
		self::addCreativeItem(Item::get(Item::GOLD_ORE, 0), self::CREATIVE_GROUP_ORE);
		self::addCreativeItem(Item::get(Item::DIAMOND_ORE, 0), self::CREATIVE_GROUP_ORE);
		self::addCreativeItem(Item::get(Item::LAPIS_ORE, 0), self::CREATIVE_GROUP_ORE);
		self::addCreativeItem(Item::get(Item::REDSTONE_ORE, 0), self::CREATIVE_GROUP_ORE);
		self::addCreativeItem(Item::get(Item::COAL_ORE, 0), self::CREATIVE_GROUP_ORE);
		self::addCreativeItem(Item::get(Item::EMERALD_ORE, 0), self::CREATIVE_GROUP_ORE);

		self::addCreativeItem(Item::get(Item::TRUNK, 0), self::CREATIVE_GROUP_LOGS);
		self::addCreativeItem(Item::get(Item::TRUNK, 1), self::CREATIVE_GROUP_LOGS);
		self::addCreativeItem(Item::get(Item::TRUNK, 2), self::CREATIVE_GROUP_LOGS);
		self::addCreativeItem(Item::get(Item::TRUNK, 3), self::CREATIVE_GROUP_LOGS);
		self::addCreativeItem(Item::get(Item::TRUNK2, 0), self::CREATIVE_GROUP_LOGS);
		self::addCreativeItem(Item::get(Item::TRUNK2, 1), self::CREATIVE_GROUP_LOGS);

		self::addCreativeItem(Item::get(Item::LEAVES, 0), self::CREATIVE_GROUP_LEAVES);
		self::addCreativeItem(Item::get(Item::LEAVES, 1), self::CREATIVE_GROUP_LEAVES);
		self::addCreativeItem(Item::get(Item::LEAVES, 2), self::CREATIVE_GROUP_LEAVES);
		self::addCreativeItem(Item::get(Item::LEAVES, 3), self::CREATIVE_GROUP_LEAVES);
		self::addCreativeItem(Item::get(Item::LEAVES2, 0), self::CREATIVE_GROUP_LEAVES);
		self::addCreativeItem(Item::get(Item::LEAVES2, 1), self::CREATIVE_GROUP_LEAVES);

		self::addCreativeItem(Item::get(Item::SAPLING, 0), self::CREATIVE_GROUP_SAPLING);
		self::addCreativeItem(Item::get(Item::SAPLING, 1), self::CREATIVE_GROUP_SAPLING);
		self::addCreativeItem(Item::get(Item::SAPLING, 2), self::CREATIVE_GROUP_SAPLING);
		self::addCreativeItem(Item::get(Item::SAPLING, 3), self::CREATIVE_GROUP_SAPLING);
		self::addCreativeItem(Item::get(Item::SAPLING, 4), self::CREATIVE_GROUP_SAPLING);
		self::addCreativeItem(Item::get(Item::SAPLING, 5), self::CREATIVE_GROUP_SAPLING);

		self::addCreativeItem(Item::get(Item::SEEDS, 0), self::CREATIVE_GROUP_SEED);
		self::addCreativeItem(Item::get(Item::PUMPKIN_SEEDS, 0), self::CREATIVE_GROUP_SEED);
		self::addCreativeItem(Item::get(Item::MELON_SEEDS, 0), self::CREATIVE_GROUP_SEED);
		self::addCreativeItem(Item::get(Item::BEETROOT_SEEDS, 0), self::CREATIVE_GROUP_SEED);

		self::addCreativeItem(Item::get(Item::WHEAT, 0), self::CREATIVE_GROUP_CROP);
		self::addCreativeItem(Item::get(Item::APPLE, 0), self::CREATIVE_GROUP_CROP);
		self::addCreativeItem(Item::get(Item::GOLDEN_APPLE, 0), self::CREATIVE_GROUP_CROP);
		self::addCreativeItem(Item::get(Item::ENCHANTED_GOLDEN_APPLE, 0), self::CREATIVE_GROUP_CROP);

		self::addCreativeItem(Item::get(Item::MELON_BLOCK, 0), self::CREATIVE_GROUP_CROP);
		self::addCreativeItem(Item::get(Item::MELON, 0), self::CREATIVE_GROUP_CROP);
		self::addCreativeItem(Item::get(Item::PUMPKIN, 0), self::CREATIVE_GROUP_CROP);
		self::addCreativeItem(Item::get(Item::LIT_PUMPKIN, 0), self::CREATIVE_GROUP_CROP);

		self::addCreativeItem(Item::get(Item::TALL_GRASS, 1), self::CREATIVE_GROUP_GRASS);
		self::addCreativeItem(Item::get(Item::TALL_GRASS, 2), self::CREATIVE_GROUP_GRASS);
		self::addCreativeItem(Item::get(Item::DANDELION, 0), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_POPPY), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_BLUE_ORCHID), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_ALLIUM), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_AZURE_BLUET), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_RED_TULIP), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_ORANGE_TULIP), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_WHITE_TULIP), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_PINK_TULIP), self::CREATIVE_GROUP_FLOWER);
		self::addCreativeItem(Item::get(Item::RED_FLOWER, Flower::TYPE_OXEYE_DAISY), self::CREATIVE_GROUP_FLOWER);

		self::addColoredCreativeItem(Item::DYE, self::CREATIVE_GROUP_DYE);

		self::addCreativeItem(Item::get(Item::BROWN_MUSHROOM, 0), self::CREATIVE_GROUP_MUSHROOM);
		self::addCreativeItem(Item::get(Item::RED_MUSHROOM, 0), self::CREATIVE_GROUP_MUSHROOM);

		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 15), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 10), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 11), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 12), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 13), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 14), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 22), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 16), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 19), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 18), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 33), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 38), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 39), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 34), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 37), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 35), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 32), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 36), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 17), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 40), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 42), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 41), self::CREATIVE_GROUP_MOBEGG);
		//self::addCreativeItem(Item::get(Item::SPAWN_EGG, 43), self::CREATIVE_GROUP_MOBEGG);

		self::addCreativeItem(Item::get(Item::LEATHER_CAP, 0), self::CREATIVE_GROUP_HELMET);
		self::addCreativeItem(Item::get(Item::CHAIN_HELMET, 0), self::CREATIVE_GROUP_HELMET);
		self::addCreativeItem(Item::get(Item::IRON_HELMET, 0), self::CREATIVE_GROUP_HELMET);
		self::addCreativeItem(Item::get(Item::DIAMOND_HELMET, 0), self::CREATIVE_GROUP_HELMET);
		self::addCreativeItem(Item::get(Item::GOLD_HELMET, 0), self::CREATIVE_GROUP_HELMET);

		self::addCreativeItem(Item::get(Item::LEATHER_TUNIC, 0), self::CREATIVE_GROUP_CHESTPLATE);
		self::addCreativeItem(Item::get(Item::CHAIN_CHESTPLATE, 0), self::CREATIVE_GROUP_CHESTPLATE);
		self::addCreativeItem(Item::get(Item::IRON_CHESTPLATE, 0), self::CREATIVE_GROUP_CHESTPLATE);
		self::addCreativeItem(Item::get(Item::DIAMOND_CHESTPLATE, 0), self::CREATIVE_GROUP_CHESTPLATE);
		self::addCreativeItem(Item::get(Item::GOLD_CHESTPLATE, 0), self::CREATIVE_GROUP_CHESTPLATE);

		self::addCreativeItem(Item::get(Item::LEATHER_PANTS, 0), self::CREATIVE_GROUP_LEGGINGS);
		self::addCreativeItem(Item::get(Item::CHAIN_LEGGINGS, 0), self::CREATIVE_GROUP_LEGGINGS);
		self::addCreativeItem(Item::get(Item::IRON_LEGGINGS, 0), self::CREATIVE_GROUP_LEGGINGS);
		self::addCreativeItem(Item::get(Item::DIAMOND_LEGGINGS, 0), self::CREATIVE_GROUP_LEGGINGS);
		self::addCreativeItem(Item::get(Item::GOLD_LEGGINGS, 0), self::CREATIVE_GROUP_LEGGINGS);

		self::addCreativeItem(Item::get(Item::LEATHER_BOOTS, 0), self::CREATIVE_GROUP_BOOTS);
		self::addCreativeItem(Item::get(Item::CHAIN_BOOTS, 0), self::CREATIVE_GROUP_BOOTS);
		self::addCreativeItem(Item::get(Item::IRON_BOOTS, 0), self::CREATIVE_GROUP_BOOTS);
		self::addCreativeItem(Item::get(Item::DIAMOND_BOOTS, 0), self::CREATIVE_GROUP_BOOTS);
		self::addCreativeItem(Item::get(Item::GOLD_BOOTS, 0), self::CREATIVE_GROUP_BOOTS);

		self::addCreativeItem(Item::get(Item::WOODEN_SWORD, 0), self::CREATIVE_GROUP_SWORD);
		self::addCreativeItem(Item::get(Item::STONE_SWORD, 0), self::CREATIVE_GROUP_SWORD);
		self::addCreativeItem(Item::get(Item::IRON_SWORD, 0), self::CREATIVE_GROUP_SWORD);
		self::addCreativeItem(Item::get(Item::DIAMOND_SWORD, 0), self::CREATIVE_GROUP_SWORD);
		self::addCreativeItem(Item::get(Item::GOLD_SWORD, 0), self::CREATIVE_GROUP_SWORD);

		self::addCreativeItem(Item::get(Item::WOODEN_AXE, 0), self::CREATIVE_GROUP_AXE);
		self::addCreativeItem(Item::get(Item::STONE_AXE, 0), self::CREATIVE_GROUP_AXE);
		self::addCreativeItem(Item::get(Item::IRON_AXE, 0), self::CREATIVE_GROUP_AXE);
		self::addCreativeItem(Item::get(Item::DIAMOND_AXE, 0), self::CREATIVE_GROUP_AXE);
		self::addCreativeItem(Item::get(Item::GOLD_AXE, 0), self::CREATIVE_GROUP_AXE);

		self::addCreativeItem(Item::get(Item::WOODEN_PICKAXE, 0), self::CREATIVE_GROUP_PICKAXE);
		self::addCreativeItem(Item::get(Item::STONE_PICKAXE, 0), self::CREATIVE_GROUP_PICKAXE);
		self::addCreativeItem(Item::get(Item::IRON_PICKAXE, 0), self::CREATIVE_GROUP_PICKAXE);
		self::addCreativeItem(Item::get(Item::DIAMOND_PICKAXE, 0), self::CREATIVE_GROUP_PICKAXE);
		self::addCreativeItem(Item::get(Item::GOLD_PICKAXE, 0), self::CREATIVE_GROUP_PICKAXE);

		self::addCreativeItem(Item::get(Item::WOODEN_SHOVEL, 0), self::CREATIVE_GROUP_SHOVEL);
		self::addCreativeItem(Item::get(Item::STONE_SHOVEL, 0), self::CREATIVE_GROUP_SHOVEL);
		self::addCreativeItem(Item::get(Item::IRON_SHOVEL, 0), self::CREATIVE_GROUP_SHOVEL);
		self::addCreativeItem(Item::get(Item::DIAMOND_SHOVEL, 0), self::CREATIVE_GROUP_SHOVEL);
		self::addCreativeItem(Item::get(Item::GOLD_SHOVEL, 0), self::CREATIVE_GROUP_SHOVEL);

		self::addCreativeItem(Item::get(Item::WOODEN_HOE, 0), self::CREATIVE_GROUP_HOE);
		self::addCreativeItem(Item::get(Item::STONE_HOE, 0), self::CREATIVE_GROUP_HOE);
		self::addCreativeItem(Item::get(Item::IRON_HOE, 0), self::CREATIVE_GROUP_HOE);
		self::addCreativeItem(Item::get(Item::DIAMOND_HOE, 0), self::CREATIVE_GROUP_HOE);
		self::addCreativeItem(Item::get(Item::GOLD_HOE, 0), self::CREATIVE_GROUP_HOE);

        for ($i = 0; $i <= 37; $i++) {
            if($i !== 1 && $i !== 2 && $i !== 3 && $i !== 4 && $i !== 5) self::addCreativeItem(Item::get(Item::ARROW, $i), self::CREATIVE_GROUP_ARROW);
        }

        for ($i = 0; $i <= 15; $i++) {
            self::addCreativeItem(Item::get(236, $i), self::CREATIVE_GROUP_CONCRETE);
        }

        for ($i = 0; $i <= 15; $i++) {
            self::addCreativeItem(Item::get(237, $i), self::CREATIVE_GROUP_CONCRETEPOWDER);
        }

		self::addCreativeItem(Item::get(Item::COOKED_FISH, 0), self::CREATIVE_GROUP_COOKEDFOOD);
		self::addCreativeItem(Item::get(Item::COOKED_FISH, 1), self::CREATIVE_GROUP_COOKEDFOOD);
		self::addCreativeItem(Item::get(Item::CAKE, 0), self::CREATIVE_GROUP_MISCFOOD);
		self::addCreativeItem(Item::get(Item::BREAD, 0), self::CREATIVE_GROUP_MISCFOOD);

        for ($i = 0; $i <= 15; $i++) {
		    self::addCreativeItem(Item::get(Item::BED, $i), self::CREATIVE_GROUP_BED);
        }

        for ($i = 0; $i <= 5; $i++) {
		    self::addCreativeItem(Item::get(Item::BOAT, $i), self::CREATIVE_GROUP_BOAT);
        }

		self::addCreativeItem(Item::get(Item::ANVIL, 0), self::CREATIVE_GROUP_ANVIL);
		self::addCreativeItem(Item::get(Item::ANVIL, 4), self::CREATIVE_GROUP_ANVIL);
		self::addCreativeItem(Item::get(Item::ANVIL, 8), self::CREATIVE_GROUP_ANVIL);

		self::addCreativeItem(Item::get(Item::CHEST, 0), self::CREATIVE_GROUP_CHEST);
		self::addCreativeItem(Item::get(Item::ENDER_CHEST, 0), self::CREATIVE_GROUP_CHEST);

		self::addCreativeItem(Item::get(Item::SIGN, 0), self::CREATIVE_GROUP_SIGN);

		self::addCreativeItem(Item::get(Item::RAIL, 0), self::CREATIVE_GROUP_RAIL);
		self::addCreativeItem(Item::get(Item::POWERED_RAIL, 0), self::CREATIVE_GROUP_RAIL);
		self::addCreativeItem(Item::get(Item::DETECTOR_RAIL, 0), self::CREATIVE_GROUP_RAIL);
		self::addCreativeItem(Item::get(Item::ACTIVATOR_RAIL, 0), self::CREATIVE_GROUP_RAIL);

		self::addCreativeItem(Item::get(Item::MINECART, 0), self::CREATIVE_GROUP_MINECART);

		self::addCreativeItem(Item::get(Item::STRUCTURE_BLOCK, 0));

		$creativeItems = new Config(Server::getInstance()->getFilePath() . "src/pocketmine/resources/creativeitems.json", Config::JSON, []);
		foreach($creativeItems->getAll() as $data){
			$item = Item::get($data["id"], $data["damage"], $data["count"], $data["nbt"]);
			if($item->getName() === "Unknown"){
				continue;
			}
			self::addCreativeItem($item);
		}
	}
	private static function addColoredCreativeItem($itemId, $creativeGroup) {
		self::addCreativeItem(Item::get($itemId, Block::COLOR_WHITE), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_ORANGE), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_MAGENTA), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_LIGHT_BLUE), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_YELLOW), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_LIME), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_PINK), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_GRAY), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_LIGHT_GRAY), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_CYAN), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_PURPLE), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_BLUE), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_BROWN), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_GREEN), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_RED), $creativeGroup);
		self::addCreativeItem(Item::get($itemId, Block::COLOR_BLACK), $creativeGroup);
	}

	private static function initFood(){
		self::$food[] = Item::COOKIE;
		self::$food[] = Item::MELON;
		self::$food[] = Item::RAW_BEEF;
		self::$food[] = Item::COOKED_BEEF;
		self::$food[] = Item::RAW_CHICKEN;
		self::$food[] = Item::COOKED_CHICKEN;
		self::$food[] = Item::CARROT;
		self::$food[] = Item::POTATO;
		self::$food[] = Item::BAKED_POTATO;
		self::$food[] = Item::PUMPKIN_PIE;
		self::$food[] = Item::BREAD;
		self::$food[] = Item::APPLE;
		self::$food[] = Item::GOLDEN_APPLE;
		self::$food[] = Item::RAW_FISH;
		self::$food[] = Item::COOKED_FISH;
		self::$food[] = Item::RAW_PORKCHOP;
		self::$food[] = Item::COOKED_PORKCHOP;
		self::$food[] = Item::RAW_MUTTON;
		self::$food[] = Item::COOKED_MUTTON;
		self::$food[] = Item::RAW_RABBIT;
		self::$food[] = Item::COOKED_RABBIT;
		self::$food[] = Item::RAW_SALMON;
		self::$food[] = Item::COOKED_SALMON;
		self::$food[] = Item::RABBIT_STEW;
		self::$food[] = Item::CHORUS_FRUIT;
	}

	public static function clearCreativeItems(){
		Item::$creative = [];
		Item::$creative110 = [];
	}

	public static function getCreativeItems($protocol){
		if($protocol >= 120){
			return Item::$creative;
		}else{
			return Item::$creative110;
		}
	}

	public static function addCreativeItem110(Item $item, $creativeGroup = self::CREATIVE_GROUP_NONE){
		Item::$creative110[] = ["item" => Item::get($item->getId(), $item->getDamage()), "group" => $creativeGroup];
	}

	public static function addCreativeItem(Item $item, $creativeGroup = self::CREATIVE_GROUP_NONE){
		Item::$creative[] = ["item" => Item::get($item->getId(), $item->getDamage()), "group" => $creativeGroup];
		if($item->getId() != 326 and $item->getId() != 327){
			Item::$creative110[] = ["item" => Item::get($item->getId(), $item->getDamage()), "group" => $creativeGroup];
		}
	}

	public static function removeCreativeItem(Item $item){
		$index = self::getCreativeItemIndex($item);
		if($index !== -1){
			unset(Item::$creative[$index]);
			unset(Item::$creative110[$index]);
		}
	}

	public static function isCreativeItem(Item $item){
		foreach(Item::$creative as $i => $d){
			if($item->equals($d["item"], !$item->isTool())){
				return true;
			}
		}

		return false;
	}

	/**
	 * @param $index
	 * @return Item
	 */
	public static function getCreativeItem($index){
		return isset(Item::$creative[$index]) ? Item::$creative[$index]["item"] : null;
	}

	/**
	 * @param Item $item
	 * @return int
	 */
	public static function getCreativeItemIndex(Item $item){
		foreach(Item::$creative as $i => $d){
			if($item->equals($d["item"], !$item->isTool())){
				return $i;
			}
		}

		return -1;
	}

	public static function get($id, $meta = 0, $count = 1, $tags = ""){
		try {
			if (!isset(self::$list[$id])) {
				if ($id < 256 && isset(Block::$list[$id]) && !is_null(Block::$list[$id])) {
					$class = Block::$list[$id];
					return (new self::$itemBlockClass(new $class($meta), $meta, $count))->setCompound($tags);
				}
				return (new Item($id, $meta, $count))->setCompound($tags);
			}
			$class = self::$list[$id];
			return (new $class($meta, $count))->setCompound($tags);
		} catch (\RuntimeException $e) {
			return (new Item($id, $meta, $count))->setCompound($tags);
		}
	}

	public static function fromString($str, $multiple = false){
		if($multiple === true){
			$blocks = [];
			foreach(explode(",", $str) as $b){
				$blocks[] = self::fromString($b, false);
			}

			return $blocks;
		}else{
			$b = explode(":", str_replace([" ", "minecraft:"], ["_", ""], trim($str)));
			if(!isset($b[1])){
				$meta = 0;
			}else{
				$meta = $b[1] & 0x7FFF;
			}

			if(defined(Item::class . "::" . strtoupper($b[0]))){
				$item = self::get(constant(Item::class . "::" . strtoupper($b[0])), $meta);
				if($item->getId() === self::AIR and strtoupper($b[0]) !== "AIR"){
					$item = self::get($b[0] & 0xFFFF, $meta);
				}
			} elseif (is_numeric($b[0])) {
				$item = self::get(((int) $b[0]) & 0xFFFF, $meta);
			}else{
				$item = self::get(self::AIR);
			}

			return $item;
		}
	}

	public function __construct($id, $meta = 0, $count = 1, $name = "Unknown", $obtainTime = null){
		$this->id = $id & 0xffff;
		$this->meta = $meta !== null ? $meta & 0x7fff : null;
		$this->count = (int) $count;
		$this->name = $name;
		if($obtainTime == null){
			$obtainTime = time();
		}
		if(!isset($this->block) and $this->id <= 0xff and isset(Block::$list[$this->id])){
			$this->block = Block::get($this->id, $this->meta);
			$this->name = $this->block->getName();
		}
		if($this->name == "Unknown" && isset(Item::$names[$this->id])){
			$this->name = Item::$names[$this->id];
		}
	}

	public function setCompound($tags){
		if($tags instanceof Compound){
			$this->setNamedTag($tags);
		}else{
			$this->tags = $tags;
			$this->cachedNBT = null;
		}

		return $this;
	}

	/**
	 * @return string
	 */
	public static function getCreativeGroups(){
		return Item::$creativeGroupData;
	}
	public function getCompound(){
		return $this->tags;
	}

	public function hasCompound(){
		return $this->tags !== "" and $this->tags !== null;
	}

	public function hasCustomBlockData(){
		if(!$this->hasCompound()){
			return false;
		}

		$tag = $this->getNamedTag();
		if(isset($tag->BlockEntityTag) and $tag->BlockEntityTag instanceof Compound){
			return true;
		}

		return false;
	}

	public function clearCustomBlockData(){
		if(!$this->hasCompound()){
			return $this;
		}
		$tag = $this->getNamedTag();

		if(isset($tag->BlockEntityTag) and $tag->BlockEntityTag instanceof Compound){
			unset($tag->display->BlockEntityTag);
			$this->setNamedTag($tag);
		}

		return $this;
	}

	public function setCustomBlockData(Compound $compound){
		$tags = clone $compound;
		$tags->setName("BlockEntityTag");

		if(!$this->hasCompound()){
			$tag = new Compound("", []);
		}else{
			$tag = $this->getNamedTag();
		}

		$tag->BlockEntityTag = $tags;
		$this->setNamedTag($tag);

		return $this;
	}

	public function getCustomBlockData(){
		if(!$this->hasCompound()){
			return null;
		}

		$tag = $this->getNamedTag();
		if(isset($tag->BlockEntityTag) and $tag->BlockEntityTag instanceof Compound){
			return $tag->BlockEntityTag;
		}

		return null;
	}

	public function hasEnchantments(){
		if(!$this->hasCompound()){
			return false;
		}

		$tag = $this->getNamedTag();
		if(isset($tag->ench)){
			$tag = $tag->ench;
			if($tag instanceof Enum){
				return true;
			}
		}

		return false;
	}

	/**
	 * @param $id
	 * @return Enchantment|null
	 */
	public function getEnchantment($id){
		if(!$this->hasEnchantments()){
			return null;
		}

		foreach($this->getNamedTag()->ench as $entry){
			if($entry["id"] === $id){
				$e = Enchantment::getEnchantment($entry["id"]);
				$e->setLevel($entry["lvl"]);
				return $e;
			}
		}

		return null;
	}

	/**
	 * @param Enchantment $ench
	 */
	public function addEnchantment(Enchantment $ench){
		if(!$this->hasCompound()){
			$tag = new Compound("", []);
		}else{
			$tag = $this->getNamedTag();
		}

		if(!isset($tag->ench)){
			$tag->ench = new Enum("ench", []);
			$tag->ench->setTagType(NBT::TAG_Compound);
		}

		$found = false;
		$maxIntIndex = -1;
		foreach($tag->ench as $k => $entry){
			if (is_numeric($k) && $k > $maxIntIndex) {
				$maxIntIndex = $k;
			}
			if($entry["id"] === $ench->getId()){
				$tag->ench->{$k} = new Compound("", [
					"id" => new ShortTag("id", $ench->getId()),
					"lvl" => new ShortTag("lvl", $ench->getLevel())
				]);
				$found = true;
				break;
			}
		}

		if(!$found){
//			$tag->ench->{count($tag->ench) + 1} = new Compound("", [
			$tag->ench->{$maxIntIndex + 1} = new Compound("", [
				"id" => new ShortTag("id", $ench->getId()),
				"lvl" => new ShortTag("lvl", $ench->getLevel())
			]);
		}

		$this->setNamedTag($tag);
	}

	/**
	 * @return Enchantment[]
	 */
	public function getEnchantments(){
		if(!$this->hasEnchantments()){
			return [];
		}

		$enchantments = [];

		foreach($this->getNamedTag()->ench as $entry){
			$e = Enchantment::getEnchantment($entry["id"]);
			$e->setLevel($entry["lvl"]);
			$enchantments[$e->getId()] = $e;
		}

		return $enchantments;
	}

	public function hasCustomName(){
		if(!$this->hasCompound()){
			return false;
		}

		$tag = $this->getNamedTag();
		if(isset($tag->display)){
			$tag = $tag->display;
			if($tag instanceof Compound and isset($tag->Name) and $tag->Name instanceof StringTag){
				return true;
			}
		}

		return false;
	}

	public function getCustomName(){
		if(!$this->hasCompound()){
			return "";
		}

		$tag = $this->getNamedTag();
		if(isset($tag->display)){
			$tag = $tag->display;
			if($tag instanceof Compound and isset($tag->Name) and $tag->Name instanceof StringTag){
				return $tag->Name->getValue();
			}
		}

		return "";
	}

	public function setCustomName($name){
		if((string) $name === ""){
			$this->clearCustomName();
		}

		if(!$this->hasCompound()){
			$tag = new Compound("", []);
		}else{
			$tag = $this->getNamedTag();
		}

		if(isset($tag->display) and $tag->display instanceof Compound){
			$tag->display->Name = new StringTag("Name", $name);
		}else{
			$tag->display = new Compound("display", [
				"Name" => new StringTag("Name", $name)
			]);
		}

		$this->setCompound($tag);

		return $this;
	}

	public function clearCustomName(){
		if(!$this->hasCompound()){
			return $this;
		}
		$tag = $this->getNamedTag();

		if(isset($tag->display) and $tag->display instanceof Compound){
			unset($tag->display->Name);
			if($tag->display->getCount() === 0){
				unset($tag->display);
			}

			$this->setNamedTag($tag);
		}

		return $this;
	}

	public function getNamedTagEntry($name){
		$tag = $this->getNamedTag();
		if($tag !== null){
			return isset($tag->{$name}) ? $tag->{$name} : null;
		}

		return null;
	}

	public function getNamedTag(){
		if(!$this->hasCompound()){
			return null;
		}elseif($this->cachedNBT !== null){
			return $this->cachedNBT;
		}
		return $this->cachedNBT = self::parseCompound($this->tags);
	}

	public function setNamedTag(Compound $tag){
		if($tag->getCount() === 0){
			return $this->clearNamedTag();
		}

		$this->cachedNBT = $tag;
		$this->tags = self::writeCompound($tag);

		return $this;
	}

	public function clearNamedTag(){
		return $this->setCompound("");
	}

	public function getCount(){
		return $this->count;
	}

	public function setCount($count){
		$this->count = (int) $count;
	}

	final public function getName(){
		return $this->hasCustomName() ? $this->getCustomName() : $this->name;
	}

	final public function canBePlaced(){
		return $this->block !== null and $this->block->canBePlaced();
	}
	final public function isPlaceable(){
		return (($this->block instanceof Block) and $this->block->isPlaceable === true);
	}
	public function getBlock(){
		if($this->block instanceof Block){
			return clone $this->block;
		}else{
			return Block::get(self::AIR);
		}
	}

	final public function getId(){
		return $this->id;
	}

	public function getDamage(){
		return $this->meta;
	}

	public function setDamage($meta){
		$this->meta = $meta !== null ? $meta & 0x7FFF : null;
	}

	public function getMaxStackSize(){
		return 64;
	}

	final public function getFuelTime(){
		if(!isset(Fuel::$duration[$this->id])){
			return null;
		}
		if($this->id !== self::BUCKET or $this->id !== self::WATER_BUCKET or $this->meta === 10){
			return Fuel::$duration[$this->id];
		}

		return null;
	}

	/**
	 * @param Entity|Block $object
	 *
	 * @return bool
	 */
	public function useOn($object){
		return false;
	}

	/**
	 * @return bool
	 */
	public function isTool(){
		return false;
	}

	/**
	 * @return int|bool
	 */
	public function getMaxDurability(){
		return false;
	}

	public function isPickaxe(){
		return false;
	}

	public function isAxe(){
		return false;
	}

	public function isSword(){
		return false;
	}

	public function isShovel(){
		return false;
	}

	public function isHoe(){
		return false;
	}

	public function isShears(){
		return false;
	}

	final public function __toString(){
		return "Item " . $this->name . " (" . $this->id . ":" . ($this->meta === null ? "?" : $this->meta) . ")x" . $this->count . ($this->hasCompound() ? " tags:0x".bin2hex($this->getCompound()) : "");
	}

	public function getDestroySpeed(Block $block, Player $player){
		return 1;
	}

	public function onActivate(Level $level, Player $player, Block $block, Block $target, $face, $fx, $fy, $fz){
		return false;
	}

	final public function equals(Item $item, $checkDamage = true, $checkCompound = true) {
		return $this->id === $item->getId() && ($checkDamage === false || $this->getDamage() === $item->getDamage()) && ($checkCompound === false || $this->getCompound() === $item->getCompound());
	}

	public final function deepEquals(Item $item, $checkDamage = true, $checkCompound = true){
		if($this->equals($item, $checkDamage, $checkCompound)){
			return true;
		}elseif($item->hasCompound() and $this->hasCompound()){
			return NBT::matchTree($this->getNamedTag(), $item->getNamedTag());
		}

		return false;
	}

	public function isFood(){
		return in_array($this->id, self::$food);
	}

	public function setObtainTime($time){
		$this->obtainTime = $time;
	}

	public function getObtainTime(){
		return $this->obtainTime;
	}

	public function isArmor(){
		return false;
	}

	public function hasLore(){
		if(!$this->hasCompound()){
			return false;
		}

		$tag = $this->getNamedTag();
		if(isset($tag->display)){
			$tag = $tag->display;
			if($tag instanceof Compound and isset($tag->Lore) and $tag->Lore instanceof Enum){
				return true;
			}
		}

		return false;
	}

	public function getLore(){
		if(!$this->hasCompound()){
			return "";
		}

		$tag = $this->getNamedTag();
		if(isset($tag->display)){
			$tag = $tag->display;
			if($tag instanceof Compound and isset($tag->Lore) and $tag->Lore instanceof Enum){
				return $tag->Lore->getValue();
			}
		}

		return [];
	}

	public function setLore($lore){
		if(!$this->hasCompound()){
			$tag = new Compound("", []);
		}else{
			$tag = $this->getNamedTag();
		}

		$loreArray = [];
		foreach ($lore as $loreText) {
			$loreArray[] = new StringTag("", $loreText);
		}

		if(isset($tag->display) and $tag->display instanceof Compound){
			$tag->display->Lore = new Enum("Lore", $loreArray);
		}else{
			$tag->display = new Compound("display", [
				"Lore" => new Enum("Lore", $loreArray)
			]);
		}

		$this->setCompound($tag);

		return $this;
	}

	public static function registerItemBlock($className) {
		if (is_a($className, ItemBlock::class, true)) {
			self::$itemBlockClass = $className;
		}
	}

	public function getCanPlaceOnBlocks() {
		return $this->canPlaceOnBlocks;
	}

	public function getCanDestroyBlocks() {
		return $this->canDestroyBlocks;
	}

	public function addCanPlaceOnBlocks($blockName) {
		$this->canPlaceOnBlocks[$blockName] = $blockName;
	}

	public function addCanDestroyBlocks($blockName) {
		$this->canDestroyBlocks[$blockName] = $blockName;
	}

}
